//array inicial
const greetings = [
  "oi",
  "ola",
  "oi tudo bem",
  "bom dia",
  "boa tarde",
  "boa noite",
  "Oi, bom dia",
  "Oi, boa tarde",
  "Oi, boa noite",
  "Oi!",
  "Oi.",
  "Oi, tudo bem?",
  "olá",
  "E aí?",
  "Oi, como vai?",
  "Olá, tudo bem?",
  "Olá, boa tarde",
  "E aí, tudo tranquilo?",
  "Bom dia!",
  "Boa tarde!",
  "Boa noite!",
  "Oi, bom dia!",
  "Oi, boa tarde!",
  "Oi, boa noite!",
  "Como está?",
  "Tudo bem contigo?",
  "Oi, como você está?",
  "Oi, como vai você?",
  "E aí, como está?",
  "Olá, como vai?",
  "Ei!",
  "Oi, tem alguém aí?",
  "Olaaa",
  "Ooiii",
  "Oláááá",
  "Bão dia",
  "Bããão dia",
  "Oiiee",
  "Boa tardii",
  "Buon giorno",
  "Opa, tudo jóiaaa?",
  "Tudu bom?",
  "Ei, tdo bom aí?",
  "Tdo ótimo!",
  "Tudibãão?",
  "Ei, tudo bem consigo?",
  "Bão, diia!",
  "Tdo show?",
  "Tudo bem, e aí contigo?",
  "Oi, como vái?",
  "Oláá, como tá tuuudo?",
  "Boa tardee, td belê?",
  "Oi, como vc tá?",
  "Eaí, td bem ctg?",
  "Oii, tudo bãão?",
  "Oiêêê",
  "Oláa, como estás?",
  "Tudo ótímo, e vc?",
  "Bão díaa!",
  "Ei, tudo jóinha?",
  "Tudibão, e contigo?",
  "Oi, tudo bemm?",
  "Olá, como vai tds?",
  "Bom diaaa, como tá?",
  "Eaí, td belezaa?",
  "Oii, como está a viida?",
  "Olá, tudo legau?",
  "Boa tardee, tudo certin?",
  "Ei, como você estás?",
  "Tudo bem consigo?",
  "Tudibãão, e tu?",
  "Oiêê, tudo jóia?",
  "Oláa, tudo ótimo?",
  "Bom dia, como estái?",
  "Eaí, tudo belezaa?",
  "Oii, como você tá?",
  "Olá, tudo em pé?",
  "Boa tarde, e aí cê tá?",
  "Oi, tudo joiaa?",
  "Ei, tudo belezinha?",
  "Tudo de boa, e contigo?",
  "Tudibão, e você?",
  "Oiêê, como tá o clima?",
  "Oláa, tudo certo aí?",
  "Bom diaa, tudo bemm?",
  "Eaí, tudo tranquilo?",
  "Oii, como você vai?",
  "Olá, tudo em ordem?",
  "Boa tarde, e aí tudo jóia?",
  "Oi, tudo na paz?",
  "Ei, tudo suave?",
  "Tudo de boa, e contigo?",
  "oi",
  "olá",
  "ola",
  "e aí",
  "tudo bem?",
  "como vai?",
  "bom dia",
  "boa tarde",
  "boa noite",
  "saudações",
  "olá amigo",
  "oi tudo bem?",
  "olá, como vai?",
  "oi, tudo tranquilo?",
  "oi pessoal",
  "e aí galera?",
  "tudo joia?",
  "oi pessoal, tudo bem?",
  "olá a todos",
  "olá pessoal",
  "como estão?",
  "bom dia a todos",
  "boa tarde amigos",
  "boa noite pessoal",
  "saudações a todos",
  "e aí pessoal, tudo bem?",
  "tudo beleza?",
  "como é que é?",
  "e aí, como estão?",
  "oi, tudo em paz?",
  "olá pessoal, tudo tranquilo?",
  "oi, como vai a vida?",
  "oi galera, tudo certo?",
  "e aí pessoal, como estão?",
  "tudo bom com vocês?",
  "olá pessoal, tudo bem por aí?",
  "oi, como você está?",
  "olá amigos, como vai isso?",
  "e aí, como anda a vida?",
  "e aí pessoal, tudo na paz?",
  "bom dia pessoal, tudo bem?",
  "oi pessoal, tudo em ordem?",
  "olá, tudo bem por aí?",
  "e aí, tudo em cima?",
  "tudo legal?",
  "e aí, como é que está?",
  "oi, como você está hoje?",
  "olá pessoal, tudo nos conformes?",
  "tudo tranquilo por aí?",
  "e aí pessoal, tudo certinho?",
  "bom dia pessoal, como vão as coisas?",
  "oi pessoal, tudo ok?",
  "olá, tudo de boa?",
  "e aí, tudo beleza?",
  "tudo em paz?",
  "oi, como você está se sentindo?",
  "olá amigos, tudo tranquilo?",
  "e aí, como vai o dia?",
  "oi pessoal, tudo na tranquilidade?",
  "olá, como estão todos?",
  "e aí, tudo bem contigo?",
  "tudo certo por aí?",
  "oi, como estão as coisas?",
  "olá pessoal, como vai a luta?",
  "e aí pessoal, tudo em ordem?",
  "bom dia a todos, como estão?",
  "oi pessoal, como vai o dia?",
  "olá, como vai essa força?",
  "e aí, como vai essa maré?",
  "tudo bem contigo?",
  "oi, como vai a vida?",
  "olá pessoal, tudo em paz?",
  "e aí, tudo joia?",
  "tudo tranquilo por aí?",
  "oi pessoal, como estão as coisas?",
  "olá, como você está se sentindo?",
  "e aí, como vai a jornada?",
  "tudo bem por aí?",
  "oi, como está o seu dia?",
  "olá amigos, como vai a rotina?",
  "e aí pessoal, tudo de boa?",
  "tudo em ordem?",
  "oi, como está a vibe?",
  "olá pessoal, como estão os ânimos?",
  "e aí, como estão os trabalhos?",
  "tudo na paz?",
  "oi pessoal, como vão os afazeres?",
  "olá, como vai essa energia?",
  "e aí, como vai o andamento?",
  "tudo beleza por aí?",
  "oi, como está a disposição?",
  "olá pessoal, como estão os projetos?",
  "e aí, como vai o clima?",
  "tudo em cima?",
  "oi pessoal, como estão as novidades?",
  "olá, como vai a inspiração?",
  "Ei",
  "Hei",
  "Ola",
  "Oie",
  "Oii",
  "Tudobem?",
  "Tudobm?",
  "Td bem?",
  "Tudoben?",
  "Tudob?",
  "Tdo bem?",
  "Tudobem?",
  "Tudobem?",
  "Td bem?",
  "Tbem?",
  "Oioi",
  "Olá, tudo bem?",
  "Oi, como vai?",
  "Bom diaaa!",
  "Boa tardeee!",
  "Boa noitiiii!",
  "Saudaçoes",
  "Eae",
  "Ola, como vai?",
  "Ola, tudo bem?",
  "Olá, tudo bom?",
  "Olá, como tá?",
  "Tudo bele?",
  "Tdo bem?",
  "Td bom?",
  "Tdo bein?",
  "Olaa",
  "Tudo belê?",
  "Oiaí",
  "Boa tardi",
  "Boa noiche",
  "Tudo bm?",
  "Bom diaa!",
  "Bnoite!",
  "Boa tardee!",
  "Bom diaa!",
  "Bom diia!",
  "Tuduu bom?",
  "Tudo bm?",
  "Eai, tudo beleza?",
  "Tudo belezaa?",
  "Tudo bom, eai?",
  "Tudo jóia?",
  "Opa, beleza?",
  "Opa, eai?",
  "Opa, tdo bem?",
  "Oiai, tudo joia?",
  "oieee",
  "salve quebrada",
  "eae mano, blz?",
  "eae mano blz",
  "suave?",
];

//desejea cadastrar => sim / registrar
const registrar = [
  "register",
  "novo usuario",
  "registro",
  "quero registrar",
  "registrar",
  "sim",
  "ativar cadastro",
  "quero ativar minha conta",
  "entrar para a comunidade",
  "quero me unir",
  "participar do grupo",
  "adicionar meu nome",
  "quero me juntar",
  "me incluir na lista",
  "quero ser parte disso",
  "aceitar convite",
  "confirmar minha inscrição",
  "quero confirmar cadastro",
  "me adicionar agora",
  "quero me associar",
  "associar-me ao grupo",
  "me integrar",
  "quero me integrar",
  "me envolver",
  "quero me envolver",
  "participar ativamente",
  "quero ser ativo no grupo",
  "me registrar para participar",
  "quero confirmar minha participação",
  "me adicionar ao projeto",
  "quero me adicionar agora",
  "me incluir no evento",
  "quero me incluir imediatamente",
  "me registrar como membro",
  "quero ser um membro ativo",
  "me inscrever e participar",
  "quero me inscrever e começar",
  "me registrar para a iniciativa",
  "quero me registrar para o evento",
  "me inscrever para a oportunidade",
  "quero me inscrever para a comunidade",
  "me registrar e começar",
  "quero me registrar e participar",
  "me inscrever para fazer parte",
  "quero me inscrever para o projeto",
  "me registrar neste instante",
  "quero me registrar já",
  "me inscrever imediatamente",
  "quero me inscrever neste momento",
  "me registrar para começar",
  "quero me registrar para fazer parte",
  "me inscrever agora para participar",
  "quero me inscrever agora para começar",
  "cadstrar",
  "reg",
  "cadastro",
  "criar conta",
  "novo cadastro",
  "quero me cadastrar",
  "cadastrar",
  "inscrever-se",
  "novo usuário",
  "registrar-se",
  "criar perfil",
  "sim, por favor",
  "vou me registrar",
  "quero participar",
  "começar",
  "iniciar",
  "criar uma conta",
  "criar login",
  "efetuar cadastro",
  "inscrição",
  "quero fazer parte",
  "quero entrar",
  "quero ser membro",
  "quero fazer o cadastro",
  "/start",
  "registro novo",
  "abrir conta",
  "fazer cadastro",
  "inscrição nova",
  "começar agora",
  "quero criar login",
  "quero inscrever-me",
  "me cadastrar agora",
  "criar nova conta",
  "registro de usuário",
  "solicitar registro",
  "participar agora",
  "quero ingressar",
  "criar perfil de usuário",
  "fazer parte",
  "quero iniciar",
  "iniciar cadastro",
  "começar a participar",
  "quero me inscrever",
  "quero criar um perfil",
  "solicitar acesso",
  "cadastro de novo usuário",
  "criar nova inscrição",
  "inscrever-se agora",
  "cadastro de conta",
  "quero fazer meu cadastro",
  "quero criar uma conta",
  "participar do registro",
  "solicitar entrada",
  "iniciar inscrição",
  "quero me cadastrar agora mesmo",
  "quero me cadastrar agora",
  "quero criar meu perfil",
  "quero criar uma conta nova",
  "quero fazer parte da comunidade",
  "inscrever-se para começar",
  "começar meu registro",
  "solicitar meu cadastro",
  "quero criar minha conta",
  "quero fazer parte disso",
  "começar a criar conta",
  "quero criar minha inscrição",
  "quero começar agora",
  "quero ingressar neste grupo",
  "quero participar do cadastro",
  "iniciar meu cadastro",
  "criar nova inscrição",
  "solicitar meu registro",
  "quero fazer parte da equipe",
  "iniciar processo de inscrição",
  "abrir novo cadastro",
  "registre-me agora",
  "quero criar meu login",
  "quero fazer meu registro",
  "quero participar",
  "quero me inscrever já",
  "quero criar meu cadastro",
  "solicitar minha inscrição",
  "quero participar do registro",
  "criar conta agora",
  "começar minha inscrição",
  "quero criar meu perfil de usuário",
  "quero me inscrever agora",
  "quero fazer meu cadastro agora",
  "quero começar a participar",
  "quero me registrar neste momento",
  "quero me inscrever para começar",
  "quero participar deste grupo",
  "começar a criar perfil",
  "quero fazer parte deste projeto",
  "iniciar meu registro",
  "criar minha conta agora",
  "quero iniciar meu cadastro",
  "quero fazer meu cadastro imediatamente",
  "quero fazer meu cadastro agora mesmo",
  "quero participar deste evento",
  "quero me inscrever imediatamente",
  "quero fazer minha inscrição agora",
  "quero me inscrever neste momento",
  "quero criar minha inscrição agora",
  "quero me inscrever agora mesmo",
  "quero criar meu perfil agora",
  "quero me inscrever para fazer parte",
  "quero me registrar agora mesmo",
  "quero me inscrever neste instante",
  "quero me registrar imediatamente",
  "quero me inscrever já mesmo",
  "quero participar do cadastro agora",
  "quero me inscrever para participar",
  "quero criar meu cadastro agora mesmo",
  "quero participar desta iniciativa",
  "quero me inscrever agora mesmo",
  "quero participar desta oportunidade",
  "quero criar minha inscrição imediatamente",
  "quero me inscrever para fazer parte agora",
  "quero me inscrever para começar agora mesmo",
  "quero me inscrever neste projeto agora",
  "quero participar desta comunidade",
  "quero me registrar agora mesmo para começar",
  "quero me registrar agora mesmo para participar",
  "quero me registrar agora mesmo para fazer parte",
  "cadastro",
  "criar conta",
  "novo cadastro",
  "quero me cadastrar",
  "inscrever-se",
  "novo usuário",
  "registrar-se",
  "criar perfil",
  "sim, por favor",
  "vou me registrar",
  "quero participar",
  "começar",
  "iniciar",
  "criar uma conta",
  "criar login",
  "efetuar cadastro",
  "inscrição",
  "quero fazer parte",
  "quero entrar",
  "quero ser membro",
  "quero fazer o cadastro",
  "cadasrto",
  "criar cona",
  "cadrasto",
  "quero resgistrar",
  "registrarr",
  "simm",
  "cadasrto",
  "criar contaa",
  "cadraastro",
  "inscreveer-se",
  "novo usuário",
  "registrar-se",
  "criarr perfil",
  "sim, por favor",
  "vou me registar",
  "querro participar",
  "começar",
  "iniciar",
  "criar uma conta",
  "criar login",
  "efetuar cadastro",
  "inscrição",
  "quero fazer parte",
  "quero entrar",
  "quero ser membro",
  "quero fazer o cadastro",
  "cadrastro",
  "criar cona",
  "cadrasto",
  "quero resgistrar",
  "registrarr",
  "simm",
  "cadasrto",
  "criaar contaa",
  "cadraastro",
  "inscreveer-se",
  "novo usuário",
  "registrar-se",
  "criarr perfil",
  "sim, por favor",
  "vou me registar",
  "querro participar",
  "começar",
  "iniciar",
  "criar uma conta",
  "criar login",
  "efetuar cadastro",
  "inscrição",
  "quero fazer parte",
  "quero entrar",
  "quero ser membro",
  "quero fazer o cadastro",
  "cadrastro",
  "criar cona",
  "cadrasto",
  "quero resgistrar",
  "registrarr",
  "simm",
  "cadasrto",
  "criaar contaa",
  "cadraastro",
  "inscreveer-se",
  "novo usuário",
  "registrar-se",
  "criarr perfil",
  "sim, por favor",
  "vou me registar",
  "querro participar",
  "começar",
  "iniciar",
  "criar uma conta",
  "criar login",
  "efetuar cadastro",
  "inscrição",
  "quero fazer parte",
  "quero entrar",
  "quero ser membro",
  "quero fazer o cadastro",
  "cadrastro",
  "criar cona",
  "cadrasto",
  "quero resgistrar",
  "registrarr",
  "simm",
  "cadasrto",
  "criaar contaa",
  "cadraastro",
  "inscreveer-se",
  "novo usuário",
  "registrar-se",
  "criarr perfil",
  "sim, por favor",
  "vou me registar",
  "querro participar",
  "começar",
  "iniciar",
  "criar uma conta",
  "criar login",
  "efetuar cadastro",
  "inscrição",
  "quero fazer parte",
  "quero entrar",
  "quero ser membro",
  "quero fazer o cadastro",
  "cadrastro",
  "criar cona",
  "cadrasto",
  "quero resgistrar",
  "registrarr",
  "simm",
  "cadasrto",
  "criaar contaa",
  "cadraastro",
  "inscreveer-se",
  "novo usuário",
  "registrar-se",
  "criarr perfil",
  "sim, por favor",
  "vou me registar",
  "querro participar",
  "começar",
  "iniciar",
  "criar uma conta",
  "criar login",
  "efetuar cadastro",
  "inscrição",
  "quero fazer parte",
  "quero entrar",
  "quero ser membro",
  "quero fazer o cadastro",
  "cadrastro",
  "criar cona",
  "cadrasto",
  "quero resgistrar",
  "registrarr",
  "simm",
  "cadasrto",
  "criaar contaa",
  "cadraastro",
  "inscreveer-se",
  "novo usuário",
  "registrar-se",
  "criarr perfil",
  "sim, por favor",
  "vou me registar",
  "querro participar",
  "começar",
  "iniciar",
  "criar uma conta",
  "criar login",
  "efetuar cadastro",
  "inscrição",
  "quero fazer parte",
  "quero entrar",
  "quero ser membro",
  "quero fazer o cadastro",
  "cadrastro",
  "criar cona",
  "cadrasto",
  "quero resgistrar",
  "registrarr",
  "simm",
  "cadasrto",
  "criaar contaa",
  "cadraastro",
  "inscreveer-se",
  "novo usuário",
  "registrar-se",
  "criarr perfil",
  "sim, por favor",
  "vou me registar",
  "querro participar",
  "começar",
  "iniciar",
  "criar uma conta",
  "criar login",
  "efetuar cadastro",
  "inscrição",
  "quero fazer parte",
  "quero entrar",
  "quero ser membro",
  "quero fazer o cadastro",
  "cadrastro",
  "criar cona",
  "cadrasto",
  "quero resgistrar",
  "registrarr",
  "simm",
  "cadasrto",
  "criaar contaa",
  "cadraastro",
  "inscreveer-se"
];

//deseja cadastrar => nao / cancelar registro
const naoRegistrar = [
  "nao register",
  "não novo usuario",
  "n",
  "não",
  "nem",
  "nãooo",
  "cancelar",
  "encerrar",
  "não registrar",
  "nao",
  "não quero",
  "nao quero",
  "não desejo",
  "não, obrigado",
  "não, valeu",
  "não, obrigada",
  "não, estou bem",
  "não preciso",
  "não é necessário",
  "não é pra mim",
  "não, já tenho conta",
  "já sou cadastrado",
  "não hoje",
  "não agora",
  "não quero me cadastrar",
  "não, obrigado mesmo",
  "não, obrigada pela oferta",
  "não, estou ocupado",
  "não, estou ocupada",
  "não, obrigado, estou só olhando",
  "não, sem interesse",
  "não quero me inscrever",
  "não, não quero",
  "não, obrigado, prefiro não",
  "não, não é para mim",
  "não, estou de boa",
  "não, já tenho cadastro",
  "não hoje, talvez depois",
  "não, talvez mais tarde",
  "não agora, obrigado",
  "não, já estou registrado",
  "não, estou fora",
  "não, não estou interessado",
  "não, não quero participar",
  "não, estou só de passagem",
  "não, já me cadastrei",
  "não, obrigado, já estou incluso",
  "não, não vou me cadastrar",
  "não, já passei por isso",
  "não, não é o momento",
  "não, não estou disponível",
  "não, estou de saída",
  "não, obrigado, prefiro não me inscrever",
  "não, já estou dentro",
  "não, isso não é para mim",
  "não, estou de fora",
  "não, não estou interessada",
  "não, não estou afim",
  "não, não é para mim mesmo",
  "não, isso não é comigo",
  "não, já passei dessa fase",
  "não, estou de partida",
  "não, obrigado, já me registrei",
  "não, já tenho uma conta",
  "não, isso não me interessa",
  "não, obrigado, mas não",
  "não, já fiz isso antes",
  "não, estou de saida",
  "não, isso não é minha praia",
  "não, já resolvi isso",
  "não, já estou nisso",
  "não, já estou envolvido",
  "não, já fiz meu cadastro",
  "não, isso não me chama atenção",
  "não, não me inscreverei",
  "não, isso não é comigo mesmo",
  "não, já passei por isso antes",
  "não, isso não me atrai",
  "não, já estou participando",
  "não, já estou dentro disso",
  "não, já me alistei",
  "não, obrigado, mas não obrigado",
  "não, já fui por esse caminho",
  "não, já resolvi isso antes",
  "não, isso não é para mim mesmo",
  "não, já tive minha cota disso",
  "não, já estou no jogo",
  "não, isso não me convence",
  "não, já estou envolvido nisso",
  "não, já me registrei",
  "não, isso não me interessa mesmo",
  "não, já estou nessa",
  "não, já dei minha cota",
  "não, isso não me atrai mesmo",
  "não, já estou por dentro",
  "não, já fiz minha parte",
  "não, isso não é para mim agora",
  "não, obrigado, mas não, obrigado",
  "não, já estou nesse barco",
  "não, isso não me pega mais",
  "não, já estou cadastrado",
  "não, isso não me interessa mais",
  "não, isso já era",
  "não, já estou envolvido nisso",
  "não, já passei por isso mesmo",
  "não, obrigado, mas não agora",
  "não, já estou nessa parada",
  "não, já fiz minha inscrição",
  "não, isso não é para mim nesse momento",
  "não, isso não é para mim agora",
  "não, já fiz minha inscrição antes",
  "não, obrigado, mas não por enquanto",
  "não, já estou nessa vibe",
  "não, já estou registrado",
  "não, isso não me anima mais",
  "não, já estou nesse meio",
  "não, obrigado, mas não estou nessa",
  "não, já fiz isso antes",
  "não, isso não é para mim agora não",
  "não, já passei por essa",
  "não, obrigado, mas não por ora",
  "não, já estou nessa parada mesmo",
  "não, isso não é para mim nesse momento",
  "não, já estou nessa vibe mesmo",
  "não, isso não me pega mais não",
  "não, já estou cadastrado mesmo",
  "não, isso não me anima mais não",
  "não, já estou nesse meio mesmo",
  "não, isso não é para mim agora não",
  "não, já fiz minha parte nisso",
  "não, isso não é para mim agora não",
  "não, isso já era mesmo",
  "não, obrigado, mas não nesse momento",
  "não, já estou nesse lance",
  "não, já estou nessa fita",
  "não, isso não me atrai mais",
  "não, já estou dentro disso mesmo",
  "não, isso não me pega mais mesmo",
  "não, isso não é para mim agora não",
  "não",
  "nao hoje",
  "nao agora",
  "nao quero me cadastrar",
  "nao, obrigado mesmo",
  "nao, obrigada pela oferta",
  "nao, estou ocupado",
  "nao, estou ocupada",
  "nao, obrigado, estou só olhando",
  "nao, sem interesse",
  "nao quero me inscrever",
  "nao, nao quero",
  "nao, obrigado, prefiro nao",
  "nao, nao é para mim",
  "nao, estou de boa",
  "nao, já tenho cadastro",
  "nao hoje, talvez depois",
  "nao, talvez mais tarde",
  "nao agora, obrigado",
  "nao, já estou registrado",
  "nao, estou fora",
  "nao, nao estou interessado",
  "nao, nao quero participar",
  "nao, estou só de passagem",
  "nao, já me cadastrei",
  "nao, obrigado, já estou incluso",
  "nao, nao vou me cadastrar",
  "nao, já passei por isso",
  "nao, nao é o momento",
  "nao, nao estou disponível",
  "nao, estou de saída",
  "nao, obrigado, prefiro nao me inscrever",
  "nao, já estou dentro",
  "nao, isso nao é para mim",
  "nao, estou de fora",
  "nao, nao estou interessada",
  "nao, nao estou afim",
  "nao, nao é para mim mesmo",
  "nao, isso nao é comigo",
  "nao, já passei dessa fase",
  "nao, estou de partida",
  "nao, obrigado, já me registrei",
  "nao, já tenho uma conta",
  "nao, isso nao me interessa",
  "nao, obrigado, mas nao",
  "nao, já fiz isso antes",
  "nao, estou de saida",
  "nao, isso nao é minha praia",
  "nao, já resolvi isso",
  "nao, já estou nisso",
  "nao, já estou envolvido",
  "nao, já fiz meu cadastro",
  "nao, isso nao me chama atenção",
  "nao, nao me inscreverei",
  "nao, isso nao é comigo mesmo",
  "nao, já passei por isso antes",
  "nao, isso nao me atrai",
  "nao, já estou participando",
  "nao, já estou dentro disso",
  "nao, já me alistei",
  "nao, obrigado, mas nao obrigado",
  "nao, já fui por esse caminho",
  "nao, já resolvi isso antes",
  "nao, isso nao é para mim mesmo",
  "nao, já tive minha cota disso",
  "nao, já estou no jogo",
  "nao, isso nao me convence",
  "nao, já estou envolvido nisso",
  "nao, já me registrei",
  "nao, isso nao me interessa mesmo",
  "nao, já estou nessa",
  "nao, já dei minha cota",
  "nao, isso nao me atrai mesmo",
  "nao, já estou por dentro",
  "nao, já fiz minha parte",
  "nao, isso nao é para mim agora",
  "nao, obrigado, mas nao, obrigado",
  "nao, já estou nesse barco",
  "nao, isso nao me pega mais",
  "nao, já estou cadastrado",
  "nao, isso nao me interessa mais",
  "nao, isso já era",
  "nao, já estou envolvido nisso",
  "nao, já passei por isso mesmo",
  "nao, obrigado, mas nao agora",
  "nao, já estou nessa parada",
  "nao, já fiz minha inscrição",
  "nao, isso nao é para mim nesse momento",
  "nao, isso nao é para mim agora",
  "nao, já fiz minha inscrição antes",
  "nao, obrigado, mas nao por enquanto",
  "nao, já estou nessa vibe",
  "nao, já estou registrado",
  "nao, isso nao me anima mais",
  "nao, já estou nesse meio",
  "nao, obrigado, mas nao estou nessa",
  "nao, já fiz isso antes",
  "nao, isso nao é para mim agora nao",
  "nao, já passei por essa",
  "nao, obrigado, mas nao por ora",
  "nao, já estou nessa parada mesmo",
  "nao, isso nao é para mim nesse momento",
  "nao, já estou nessa vibe mesmo",
  "nao, isso nao me pega mais nao",
  "nao, já estou cadastrado mesmo",
  "nao, isso nao me anima mais nao",
  "nao, já estou nesse meio mesmo",
  "nao, isso nao é para mim agora nao",
  "nao, já fiz minha parte nisso",
  "nao, isso nao é para mim agora nao",
  "nao, isso já era mesmo",
  "nao, obrigado, mas nao nesse momento",
  "nao, já estou nesse lance",
  "nao, já estou nessa fita",
  "nao, isso nao me atrai mais",
  "nao, já estou dentro disso mesmo",
  "nao, isso nao me pega mais mesmo",
  "nao, isso nao é para mim agora nao",
  "nao",
  
]

//marcar consulta
const consultas = [
  "nova",
  "vamos marcar",
  "bora marcar",
  "marca, mano",
  "marca",
  "marcar uma nova",
  "nova consulta",
  "agendar consulta",
  "agendar",
  "consulta",
  "marcar consulta",
  "consultar",
  "marcar",
  "sim",
  "marcar uma nova consulta",
  "s",
  "quero",
  "quer",
  "claro",
  "marcar hora",
  "marcar horário",
  "marcar reunião",
  "consultar disponibilidade",
  "marcar compromisso",
  "agendar horário",
  "agendar compromisso",
  "consultar agenda",
  "reservar horário",
  "reservar consulta",
  "fazer agendamento",
  "solicitar horário",
  "solicitar consulta",
  "marcar sessão",
  "agendar sessão",
  "reservar sessão",
  "quero marcar",
  "quero agendar",
  "quero fazer uma consulta",
  "outra",
  "quero marcar uma consulta",
  "vamos marcar",
  "marque",
  "marc",
  "mar",
  "nova",
  "vamos marcar",
  "bora marcar",
  "marca, mano",
  "marca",
  "marcar uma nova",
  "nova consulta",
  "agendar consulta",
  "agendar",
  "consulta",
  "marcar consulta",
  "consultar",
  "marcar",
  "sim",
  "marcar uma nova consulta",
  "s",
  "quero",
  "quer",
  "claro",
  "marcar hora",
  "marcar horário",
  "marcar reunião",
  "consultar disponibilidade",
  "marcar compromisso",
  "agendar horário",
  "agendar compromisso",
  "consultar agenda",
  "reservar horário",
  "reservar consulta",
  "fazer agendamento",
  "solicitar horário",
  "solicitar consulta",
  "marcar sessão",
  "agendar sessão",
  "reservar sessão",
  "quero marcar",
  "quero agendar",
  "quero fazer uma consulta",
  "outra",
  "quero marcar uma consulta",
  "vamos marcar",
  "marque",
  "marc",
  "mar",
  "nova",
  "marcar uma nova",
  "marcar um horário",
  "marcar um encontro",
  "marcar um compromisso",
  "agendar uma reunião",
  "agendar uma consulta",
  "agendar um horário",
  "consultar horário disponível",
  "consultar agenda disponível",
  "reservar um horário",
  "reservar uma consulta",
  "reservar uma sessão",
  "solicitar um horário",
  "solicitar uma consulta",
  "solicitar uma reunião",
  "marcar uma sessão de",
  "agendar uma sessão de",
  "reservar uma sessão de",
  "quero marcar uma sessão de",
  "quero agendar uma sessão de",
  "quero fazer uma sessão de",
  "marque uma nova",
  "marque um horário",
  "marque um encontro",
  "marque um compromisso",
  "agende uma reunião",
  "agende uma consulta",
  "agende um horário",
  "consulte horários disponíveis",
  "consulte agendas disponíveis",
  "reserve um horário",
  "reserve uma consulta",
  "reserve uma sessão",
  "solicite um horário",
  "solicite uma consulta",
  "solicite uma reunião",
  "marque uma sessão de",
  "agende uma sessão de",
  "reserve uma sessão de",
  "quero marcar uma sessão de",
  "quero agendar uma sessão de",
  "quero fazer uma sessão de",
  "agendar uma visita",
  "marcar uma visita",
  "solicitar uma visita",
  "quero marcar uma visita",
  "quero agendar uma visita",
  "quero fazer uma visita",
  "consultar disponibilidade de horário",
  "consultar horários disponíveis",
  "consultar agenda de horários",
  "reservar horário disponível",
  "solicitar horário disponível",
  "marcar consulta médica",
  "agendar consulta médica",
  "agendar uma consulta médica",
  "marcar consulta com",
  "agendar consulta com",
  "agendar consulta para",
  "reservar consulta médica",
  "solicitar consulta médica",
  "marcar exame",
  "agendar exame",
  "agendar um exame",
  "reservar exame",
  "solicitar exame",
  "quero marcar um exame",
  "quero agendar um exame",
  "quero fazer um exame",
  "marcar uma visita técnica",
  "agendar visita técnica",
  "agendar uma visita técnica",
  "reservar visita técnica",
  "solicitar visita técnica",
  "quero marcar uma visita técnica",
  "quero agendar uma visita técnica",
  "quero fazer uma visita técnica",
  "marcar uma entrevista",
  "agendar entrevista",
  "agendar uma entrevista",
  "reservar entrevista",
  "solicitar entrevista",
  "quero marcar uma entrevista",
  "quero agendar uma entrevista",
  "quero fazer uma entrevista",
  "marcar uma consulta para hoje",
  "agendar consulta para hoje",
  "reservar consulta para hoje",
  "solicitar consulta para hoje",
  "marcar consulta para amanhã",
  "agendar consulta para amanhã",
  "reservar consulta para amanhã",
  "solicitar consulta para amanhã",
  "marcar consulta para esta semana",
  "agendar consulta para esta semana",
  "reservar consulta para esta semana",
  "solicitar consulta para esta semana",
  "marcar consulta para a próxima semana",
  "agendar consulta para a próxima semana",
  "reservar consulta para a próxima semana",
  "solicitar consulta para a próxima semana",
  "marcar consulta o mais rápido possível",
  "agendar consulta o mais rápido possível",
  "reservar consulta o mais rápido possível",
  "solicitar consulta o mais rápido possível",
  "marcar consulta urgente",
  "agendar consulta urgente",
  "reservar consulta urgente",
  "solicitar consulta urgente",
  "marcar consulta imediata",
  "agendar consulta imediata",
  "reservar consulta imediata",
  "solicitar consulta imediata",
  "marcar uma consulta em",
  "agendar uma consulta em",
  "reservar uma consulta em",
  "solicitar uma consulta em",
  "marcar uma consulta para",
  "agendar uma consulta para",
  "reservar uma consulta para",
  "solicitar uma consulta para",
  "marcar uma consulta com",
  "agendar uma consulta com",
  "reservar uma consulta com",
  "solicitar uma consulta com",
  "marcar uma consulta em",
  "agendar uma consulta em",
  "reservar uma consulta em",
  "solicitar uma consulta em",
  "marcar uma consulta na",
  "agendar uma consulta na",
  "reservar uma consulta na",
  "solicitar uma consulta na",
  "marcar uma consulta para hoje em",
  "agendar uma consulta para hoje em",
  "reservar uma consulta para hoje em",
  "solicitar uma consulta para hoje em",
  "marcar uma",
    "nova",
    "vamos marcar",
    "bora marcar",
    "marca, mano",
    "marca",
    "marcar uma nova",
    "nova consulta",
    "agendar consulta",
    "agendar",
    "consulta",
    "marcar consulta",
    "consultar",
    "marcar",
    "sim",
    "marcar uma nova consulta",
    "s",
    "quero",
    "quer",
    "claro",
    "marcar hora",
    "marcar horário",
    "marcar reunião",
    "consultar disponibilidade",
    "marcar compromisso",
    "agendar horário",
    "agendar compromisso",
    "consultar agenda",
    "reservar horário",
    "reservar consulta",
    "fazer agendamento",
    "solicitar horário",
    "solicitar consulta",
    "marcar sessão",
    "agendar sessão",
    "reservar sessão",
    "quero marcar",
    "quero agendar",
    "quero fazer uma consulta",
    "outra",
    "quero marcar uma consulta",
    "vamos marcar",
    "marque",
    "marc",
    "mar",
    "nova",
    "marcar uma nova",
    "marcar um horário",
    "marcar um encontro",
    "marcar um compromisso",
    "agendar uma reunião",
    "agendar uma consulta",
    "agendar um horário",
    "consultar horário disponível",
    "consultar agenda disponível",
    "reservar um horário",
    "reservar uma consulta",
    "reservar uma sessão",
    "solicitar um horário",
    "solicitar uma consulta",
    "solicitar uma reunião",
    "marcar uma sessão de",
    "agendar uma sessão de",
    "reservar uma sessão de",
    "quero marcar uma sessão de",
    "quero agendar uma sessão de",
    "quero fazer uma sessão de",
    "marque uma nova",
    "marque um horário",
    "marque um encontro",
    "marque um compromisso",
    "agende uma reunião",
    "agende uma consulta",
    "agende um horário",
    "consulte horários disponíveis",
    "consulte agendas disponíveis",
    "reserve um horário",
    "reserve uma consulta",
    "reserve uma sessão",
    "solicite um horário",
    "solicite uma consulta",
    "solicite uma reunião",
    "marque uma sessão de",
    "agende uma sessão de",
    "reserve uma sessão de",
    "quero marcar uma sessão de",
    "quero agendar uma sessão de",
    "quero fazer uma sessão de",
    "agendar uma visita",
    "marcar uma visita",
    "solicitar uma visita",
    "quero marcar uma visita",
    "quero agendar uma visita",
    "quero fazer uma visita",
    "consultar disponibilidade de horário",
    "consultar horários disponíveis",
    "consultar agenda de horários",
    "reservar horário disponível",
    "solicitar horário disponível",
    "marcar consulta médica",
    "agendar consulta médica",
    "agendar uma consulta médica",
    "marcar consulta com",
    "agendar consulta com",
    "agendar consulta para",
    "reservar consulta médica",
    "solicitar consulta médica",
    "marcar exame",
    "agendar exame",
    "agendar um exame",
    "reservar exame",
    "solicitar exame",
    "quero marcar um exame",
    "quero agendar um exame",
    "quero fazer um exame",
    "marcar uma visita técnica",
    "agendar visita técnica",
    "agendar uma visita técnica",
    "reservar visita técnica",
    "solicitar visita técnica",
    "quero marcar uma visita técnica",
    "quero agendar uma visita técnica",
    "quero fazer uma visita técnica",
    "marcar uma entrevista",
    "agendar entrevista",
    "agendar uma entrevista",
    "reservar entrevista",
    "solicitar entrevista",
    "quero marcar uma entrevista",
    "quero agendar uma entrevista",
    "quero fazer uma entrevista",
    "marcar uma consulta para hoje",
    "agendar consulta para hoje",
    "reservar consulta para hoje",
    "solicitar consulta para hoje",
    "marcar consulta para amanhã",
    "agendar consulta para amanhã",
    "reservar consulta para amanhã",
    "solicitar consulta para amanhã",
    "marcar consulta para esta semana",
    "agendar consulta para esta semana",
    "reservar consulta para esta semana",
    "solicitar consulta para esta semana",
    "marcar consulta para a próxima semana",
    "agendar consulta para a próxima semana",
    "reservar consulta para a próxima semana",
    "solicitar consulta para a próxima semana",
    "marcar consulta o mais rápido possível",
    "agendar consulta o mais rápido possível",
    "reservar consulta o mais rápido possível",
    "solicitar consulta o mais rápido possível",
    "marcar consulta urgente",
    "agendar consulta urgente",
    "reservar consulta urgente",
    "solicitar consulta urgente",
    "marcar consulta imediata",
    "agendar consulta imediata",
    "reservar consulta imediata",
    "solicitar consulta imediata",
    "marcar uma consulta em",
    "agendar uma consulta em",
    "reservar uma consulta em",
    "solicitar uma consulta em",
    "marcar uma consulta para",
    "agendar uma consulta para",
    "reservar uma consulta para",
    "solicitar uma consulta para",
    "marcar uma consulta com",
    "agendar uma consulta com",
    "reservar uma consulta com",
    "solicitar uma consulta com",
    "marcar uma consulta em",
    "agendar uma consulta em",
    "reservar uma consulta em",
    "solicitar uma consulta em",
    "marcar uma consulta na",
    "agendar uma consulta na",
    "reservar uma consulta na",
    "solicitar uma consulta na",
    "marcar uma consulta para hoje em",
    "agendar uma consulta para hoje em",
    "reservar uma consulta para hoje em",
    "solicitar uma consulta para hoje em",
    "marcar uma",
    "agendar uma",
    "reservar uma",
    "solicitar uma",
    "marcar uma consulta para hoje em",
    "agendar uma consulta para hoje em",
    "reservar uma consulta para hoje em",
    "solicitar uma consulta para hoje em",
    "marcar uma consulta para amanhã em",
    "agendar uma consulta para amanhã em",
    "reservar uma consulta para amanhã em",
    "solicitar uma consulta para amanhã em",
    "marcar uma consulta para esta semana em",
    "agendar uma consulta para esta semana em",
    "reservar uma consulta para esta semana em",
    "solicitar uma consulta para esta semana em",
    "marcar uma consulta para a próxima semana em",
    "agendar uma consulta para a próxima semana em",
    "reservar uma consulta para a próxima semana em",
    "solicitar uma consulta para a próxima semana em",
    "marcar uma consulta o mais rápido possível em",
    "agendar uma consulta o mais rápido possível em",
    "reservar uma consulta o mais rápido possível em",
    "solicitar uma consulta o mais rápido possível em",
    "marcar uma consulta urgente em",
    "agendar uma consulta urgente em",
    "reservar uma consulta urgente em",
    "solicitar uma consulta urgente em",
    "marcar uma consulta imediata em",
    "agendar uma consulta imediata em",
    "reservar uma consulta imediata em",
    "solicitar uma consulta imediata em",
    "marcar uma consulta em",
    "agendar uma consulta em",
    "reservar uma consulta em",
    "solicitar uma consulta em",
    "marcar uma consulta para",
    "agendar uma consulta para",
    "reservar uma consulta para",
    "solicitar uma consulta para",
    "marcar uma consulta com",
    "agendar uma consulta com",
    "reservar uma consulta com",
    "solicitar uma consulta com",
    "marcar uma consulta em",
    "agendar uma consulta em",
    "reservar uma consulta em",
    "solicitar uma consulta em",
    "marcar uma consulta na",
    "agendar uma consulta na",
    "reservar uma consulta na",
    "solicitar uma consulta na",
    "marcar uma consulta para hoje em",
    "agendar uma consulta para hoje em",
    "reservar uma consulta para hoje em",
    "solicitar uma consulta para hoje em",
    "marcar uma consulta para amanhã em",
    "agendar uma consulta para amanhã em",
    "reservar uma consulta para amanhã em",
    "solicitar uma consulta para amanhã em",
    "marcar uma consulta para esta semana em",
    "agendar uma consulta para esta semana em",
    "reservar uma consulta para esta semana em",
    "solicitar uma consulta para esta semana em",
    "marcar uma consulta para a próxima semana em",
    "agendar uma consulta para a próxima semana em",
    "reservar uma consulta para a próxima semana em",
    "solicitar uma consulta para a próxima semana em",
    "marcar uma consulta o mais rápido possível em",
    "agendar uma consulta o mais rápido possível em",
    "reservar uma consulta o mais rápido possível em",
    "solicitar uma consulta o mais rápido possível em",
    "marcar uma consulta urgente em",
    "agendar uma consulta urgente em",
    "reservar uma consulta urgente em",
    "solicitar uma consulta urgente em",
    "marcar uma consulta imediata em",
    "agendar uma consulta imediata em",
    "reservar uma consulta imediata em",
    "solicitar uma consulta imediata em",
    "marcar uma consulta em",
    "agendar uma consulta em",
    "reservar uma consulta em",
    "solicitar uma consulta em",
    "marcar uma consulta para",
    "agendar uma consulta para",
    "reservar uma consulta para",
    "solicitar uma consulta para",
    "marcar uma consulta com",
    "agendar uma consulta com",
    "reservar uma consulta com",
    "solicitar uma consulta com",
    "marcar uma consulta em",
    "agendar uma consulta em",
    "reservar uma consulta em",
    "solicitar uma consulta em",
    "marcar uma consulta na",
    "agendar uma consulta na",
    "reservar uma consulta na",
    "solicitar uma consulta na",
    "marcar uma consulta para hoje em",
    "agendar uma consulta para hoje em",
    "reservar uma consulta para hoje em",
    "solicitar uma consulta para hoje em",
    "marcar uma consulta para amanhã em",
    "agendar uma consulta para amanhã em",
    "reservar uma consulta para amanhã em",
    "solicitar uma consulta para amanhã em",
    "marcar uma consulta para esta semana em",
    "agendar uma consulta para esta semana em",
    "reservar uma consulta para esta semana em",
    "solicitar uma consulta para esta semana em",
    "marcar uma consulta para a próxima semana em",
    "agendar uma consulta para a próxima semana em",
    "reservar uma consulta para a próxima semana em",
    "solicitar uma consulta para a próxima semana em",
    "marcar uma consulta o mais rápido possível em",
    "agendar uma consulta o mais rápido possível em",
    "reservar uma consulta o mais rápido possível em",
    "solicitar uma consulta o mais rápido possível em",
    "marcar uma consulta urgente em",
    "agendar uma consulta urgente em",
    "reservar uma consulta urgente em",
    "solicitar uma consulta urgente em",
    "marcar uma consulta imediata em",
    "agendar uma consulta imediata em",
    "reservar uma consulta imediata em",
    "solicitar uma consulta imediata em",
    "nova marcação de consulta",
    "marcar uma nova consulta",
    "agendamento de consulta",
    "agendar uma nova consulta",
    "novo horário de consulta",
    "nova consulta marcada",
    "novo agendamento de consulta",
    "nova marcação de horário de consulta",
    "agendar uma consulta médica",
    "marcar uma consulta para hoje",
    "agendar uma consulta para hoje",
    "reservar uma consulta para hoje",
    "solicitar uma consulta para hoje",
    "marcar uma consulta para amanhã",
    "agendar uma consulta para amanhã",
    "reservar uma consulta para amanhã",
    "solicitar uma consulta para amanhã",
    "marcar uma consulta para esta semana",
    "agendar uma consulta para esta semana",
    "reservar uma consulta para esta semana",
    "solicitar uma consulta para esta semana",
    "marcar uma consulta para a próxima semana",
    "agendar uma consulta para a próxima semana",
    "reservar uma consulta para a próxima semana",
    "solicitar uma consulta para a próxima semana",
    "marcar uma consulta o mais rápido possível",
    "agendar uma consulta o mais rápido possível",
    "reservar uma consulta o mais rápido possível",
    "solicitar uma consulta o mais rápido possível",
    "marcar uma consulta urgente",
    "agendar uma consulta urgente",
    "reservar uma consulta urgente",
    "solicitar uma consulta urgente",
    "marcar uma consulta imediata",
    "agendar uma consulta imediata",
    "reservar uma consulta imediata",
    "solicitar uma consulta imediata",
    "marcar uma consulta em",
    "agendar uma consulta em",
    "reservar uma consulta em",
    "solicitar uma consulta em",
    "marcar uma consulta para",
    "agendar uma consulta para",
    "reservar uma consulta para",
    "solicitar uma consulta para",
    "marcar uma consulta com",
    "agendar uma consulta com",
    "reservar uma consulta com",
    "solicitar uma consulta com",
    "marcar uma consulta em",
    "agendar uma consulta em",
    "reservar uma consulta em",
    "solicitar uma consulta em",
    "marcar uma consulta na",
    "agendar uma consulta na",
    "reservar uma consulta na",
    "solicitar uma consulta na",
    "marcar uma consulta para hoje em",
    "agendar uma consulta para hoje em",
    "reservar uma consulta para hoje em",
    "solicitar uma consulta para hoje em",
    "marcar uma consulta para amanhã em",
    "agendar uma consulta para amanhã em",
    "reservar uma consulta para amanhã em",
    "solicitar uma consulta para amanhã em",
    "marcar uma consulta para esta semana em",
    "agendar uma consulta para esta semana em",
    "reservar uma consulta para esta semana em",
    "solicitar uma consulta para esta semana em",
    "marcar uma consulta para a próxima semana em",
    "agendar uma consulta para a próxima semana em",
    "reservar uma consulta para a próxima semana em",
    "solicitar uma consulta para a próxima semana em",
    "marcar uma consulta o mais rápido possível em",
    "agendar uma consulta o mais rápido possível em",
    "reservar uma consulta o mais rápido possível em",
    "solicitar uma consulta o mais rápido possível em",
    "marcar uma consulta urgente em",
    "agendar uma consulta urgente em",
    "reservar uma consulta urgente em",
    "solicitar uma consulta urgente em",
    "marcar uma consulta imediata em",
    "agendar uma consulta imediata em",
    "reservar uma consulta imediata em",
    "solicitar uma consulta imediata em",
    "nova marcação de consulta",
    "marcar uma nova consulta",
    "agendamento de consulta",
    "agendar uma nova consulta",
    "novo horário de consulta",
    "nova consulta marcada",
    "novo agendamento de consulta",
    "nova marcação de horário de consulta",
    "agendar consulta médica",
    "marcar consulta para hoje",
    "agendar consulta para hoje",
    "reservar consulta para hoje",
    "solicitar consulta para hoje",
    "marcar consulta para amanhã",
    "agendar consulta para amanhã",
    "reservar consulta para amanhã",
    "solicitar consulta para amanhã",
    "marcar consulta para esta semana",
    "agendar consulta para esta semana",
    "reservar consulta para esta semana",
    "solicitar consulta para esta semana",
    "marcar consulta para a próxima semana",
    "agendar consulta para a próxima semana",
    "reservar consulta para a próxima semana",
    "solicitar consulta para a próxima semana",
    "marcar consulta o mais rápido possível",
    "agendar consulta o mais rápido possível",
    "reservar consulta o mais rápido possível",
    "solicitar consulta o mais rápido possível",
    "marcar consulta urgente",
    "agendar consulta urgente",
    "reservar consulta urgente",
    "solicitar consulta urgente",
    "marcar consulta imediata",
    "agendar consulta imediata",
    "reservar consulta imediata",
    "solicitar consulta imediata",
    "marcar consulta em",
    "agendar consulta em",
    "reservar consulta em",
    "solicitar consulta em",
    "marcar consulta para",
    "agendar consulta para",
    "reservar consulta para",
    "solicitar consulta para",
    "marcar consulta com",
    "agendar consulta com",
    "reservar consulta com",
    "solicitar consulta com",
    "marcar consulta em",
    "agendar consulta em",
    "reservar consulta em",
    "solicitar consulta em",
    "marcar consulta na",
    "agendar consulta na",
    "reservar consulta na",
    "solicitar consulta na",
    "marcar consulta para hoje em",
    "agendar consulta para hoje em",
    "reservar consulta para hoje em",
    "solicitar consulta para hoje em",
    "marcar consulta para amanhã em",
    "agendar consulta para amanhã em",
    "reservar consulta para amanhã em",
    "solicitar consulta para amanhã em",
    "marcar consulta para esta semana em",
    "agendar consulta para esta semana em",
    "reservar consulta para esta semana em",
    "solicitar consulta para esta semana em",
    "marcar consulta para a próxima semana em",
    "agendar consulta para a próxima semana em",
    "reservar consulta para a próxima semana em",
    "solicitar consulta para a próxima semana em",
    "marcar consulta o mais rápido possível em",
    "agendar consulta o mais rápido possível em",
    "reservar consulta o mais rápido possível em",
    "solicitar consulta o mais rápido possível em",
    "marcar consulta urgente em",
    "agendar consulta urgente em",
    "reservar consulta urgente em",
    "solicitar consulta urgente em",
    "marcar consulta imediata em",
    "agendar consulta imediata em",
    "reservar consulta imediata em",
    "solicitar consulta imediata em",
    "nova marcação de consulta",
    "marcar uma nova consulta",
    "agendamento de consulta",
    "agendar uma nova consulta",
    "novo horário de consulta",
    "nova consulta marcada",
    "novo agendamento de consulta",
    "nova marcação de horário de consulta"
];

//ver consulta
const verConsultas = [
  "ver",
  "quero ver uma consulta",
  "quero ver minhas consultas",
  "quero ver",
  "liste para mim",
  "lista",
  "consultas",
  "minhas consultas",
  "consulta",
  "consult",
  "agendadas",
  "ver minhas consultas",
  "quero ver",
  "mostrar",
  "ver consulta",
  "marcada",
  "visualizar",
  "verificar",
  "exibir",
  "verificar consultas",
  "verificar compromissos",
  "verificar agendamentos",
  "verificar horários",
  "mostrar consultas",
  "mostrar agendamentos",
  "ver histórico de consultas",
  "consultar histórico",
  "verificar consultas marcadas",
  "mostrar consultas agendadas",
  "ver consultas pendentes",
  "ver consultas confirmadas",
  "ver minhas marcações",
  "ver meus agendamentos",
  "ver minhas reservas",
  "marcadas",
  "ver consultas",
  "quer ver quais consultas eu tenho",
  "quer ver",
  "vão ve",
  "vao ve"
];

//confirmar a consulta => sim
const confirmar = [
  "confirmar",
  "confirmae",
  "confirma",
  "pode pa",
  "vai logo",
  "bora mano",
  "lets go",
  "s",
  "sim",
  "marcar",
  "agendar",
  "sim, confirmar",
  "marcar consulta",
  "sim, marcar",
  "agendar consulta",
  "marcar uma nova consulta",
  "confirmo",
  "confirmado",
  "sim, por favor",
  "sim, claro",
  "ok",
  "tudo certo",
  "certo",
  "confirmado com sucesso",
  "fechar",
  "concluir",
  "validar",
  "aceitar",
  "agende",
  "marque",
  "sim, quero",
  "sim, desejo",
  "marque para mim",
  "agende para mim",
  "marque agora",
  "agende agora",
  "desejo confirmar",
  "quero confirmar",
  "gostaria de confirmar",
  "quero agendar",
  "gostaria de agendar",
  "desejo agendar",
  "quero marcar",
  "gostaria de marcar",
  "desejo marcar",
  "quero confirmar agora",
  "gostaria de confirmar agora",
  "desejo confirmar agora",
  "quero agendar agora",
  "gostaria de agendar agora",
  "desejo agendar agora",
  "quero marcar agora",
  "gostaria de marcar agora",
  "desejo marcar agora",
  "quero confirmar minha presença",
  "gostaria de confirmar minha presença",
  "desejo confirmar minha presença",
  "quero confirmar minha presença agora",
  "gostaria de confirmar minha presença agora",
  "desejo confirmar minha presença agora",
  "quero confirmar minha participação",
  "gostaria de confirmar minha participação",
  "desejo confirmar minha participação",
  "quero confirmar minha participação agora",
  "gostaria de confirmar minha participação agora",
  "desejo confirmar minha participação agora",
  "quero confirmar minha inscrição",
  "gostaria de confirmar minha inscrição",
  "desejo confirmar minha inscrição",
  "quero confirmar minha inscrição agora",
  "gostaria de confirmar minha inscrição agora",
  "desejo confirmar minha inscrição agora",
  // Adições relacionadas a "confirmar minha consulta":
  "confirmar minha consulta",
  "quero confirmar minha consulta",
  "gostaria de confirmar minha consulta",
  "confirmar consulta",
  "quero confirmar consulta",
  "gostaria de confirmar consulta",
  "confirmar consulta médica",
  "quero confirmar consulta médica",
  "gostaria de confirmar consulta médica",
  "confirmar consulta com o médico",
  "quero confirmar consulta com o médico",
  "gostaria de confirmar consulta com o médico",
  "confirmar horário da consulta",
  "quero confirmar horário da consulta",
  "gostaria de confirmar horário da consulta",
  "confirmar data da consulta",
  "quero confirmar data da consulta",
  "gostaria de confirmar data da consulta",
  "confirmar consulta agora",
  "quero confirmar consulta agora",
  "gostaria de confirmar consulta agora",
  "confirmar minha consulta agora",
  "quero confirmar minha consulta agora",
  "gostaria de confirmar minha consulta agora",
  "confirmar minha consulta médica agora",
  "quero confirmar minha consulta médica agora",
  "gostaria de confirmar minha consulta médica agora",
  "confirmar consulta com o médico agora",
  "quero confirmar consulta com o médico agora",
  "gostaria de confirmar consulta com o médico agora"
];

//confirmar a consulta => nao
const naoMarcar = [
  "nao",
  "no",
  "n",
  "nâo",
  "nem",
  "nãoo",
  "cancelar",
  "encerrar",
  "não registrar",
  "nao",
  "não confirmo",
  "não confirmado",
  "não quero",
  "não desejo",
  "não, obrigado",
  "não, valeu",
  "não, obrigada",
  "não, estou bem",
  "não preciso",
  "não é necessário",
  "não é pra mim",
  "não, obrigado mesmo",
  "não, obrigada pela oferta",
  "não, estou ocupado",
  "não, estou ocupada",
  "não, obrigado, estou só olhando",
  "não, sem interesse",
  "não agora",
  "não, obrigado, já estou agendado",
  "não, já tenho consulta",
  "nenhum dos dois",
  "os dois",
  "nenhum",
  "nem",
  "nop"
];

const encerrar = [
  "obrigado",
"obg",
"ok, obrigado",
"preciso que encerre",
"quero encerrar",
"chega",
"flw",
"ok obrigado",
"okay",
"ok valeu",
"ok meu irmao",
"ok, obg",
"ok, perfeito",
"ok, tamo junto",
"ok",
"pode encerrar",
"bjs",
"obri",
"ate mais",
"tchau",
"até",
"até mais",
"valeu",
"tamo junto",
"tmj",
"encerrar",
"terminar",
"finalizar",
"fechar",
"sair",
"cancelar atendimento",
"parar",
"adeus",
"até logo",
"sair do chat",
"sair da conversa",
"desligar",
"encerrar chat",
"encerrar conversa",
"adeus",
"fim",
"cancelar operação",
"voltar mais tarde",
"cancelar ação",
"sair agora",
"concluir",
"despedir",
"deixar",
"sair do sistema",
"terminar sessão",
"encerrar aplicativo",
"voltar ao menu principal",
"cancelar tudo",
"desconectar",
"voltar mais tarde",
"não quero mais",
"cancelar",
"sair daqui",
"dizer tchau",
"quero encerrar",
"quero desligar",
"quero sair",
"desisti",
"sai pra la",
"me enganei",
"obrigada",
"valeu mesmo",
"vlw",
"tmj",
"tchauzinho",
"falou",
"obrigado por tudo",
"beijos",
"até breve",
"até logo",
"volte sempre",
"até a próxima",
"grato",
"sair do sistema",
"encerrar sessão",
"voltar ao início",
"cancelar processo",
"terminar conversa",
"finalizar chat",
"desconectar-se",
"sair agora mesmo",
"encerrar interação",
"concluir operação",
"terminar atendimento",
"finalizar ação",
"fechar janela",
"encerrar conversação",
"interromper",
"parar agora",
"parar conversa",
"sair definitivamente",
"cancelar solicitação",
"encerrar diálogo",
"encerrar comunicação",
"encerrar interação",
"finalizar sessão",
"voltar ao ponto inicial",
"cancelar processo",
"terminar diálogo",
"finalizar comunicação",
"desconectar-se",
"sair imediatamente",
"encerrar interação",
"concluir atendimento",
"terminar ação",
"fechar chat",
"despedir-se",
"cancelar pedido",
"encerrar conexão",
"parar imediatamente",
"parar interação",
"sair de vez",
"cancelar operação",
"encerrar discussão",
"encerrar interação",
"finalizar interação",
"desligar agora",
"encerrar chat agora",
"terminar chat",
"encerrar chamada",
"finalizar atendimento",
"terminar conversação",
"fechar atendimento",
"encerrar atendimento",
"desconectar-se agora",
"encerrar interação agora",
"concluir diálogo",
"encerrar chat imediatamente",
"terminar sessão agora",
"finalizar conversa agora",
"encerrar interação imediatamente",
"concluir atendimento agora",
"terminar ação agora",
"fechar chat agora",
"despedir-se agora",
"cancelar pedido agora",
"encerrar conexão agora",
"parar imediatamente",
"parar interação agora",
"sair de vez agora",
"cancelar operação agora",
"encerrar discussão agora",
"encerrar interação agora",
"finalizar interação agora",
"desligar agora",
"encerrar chat agora",
"terminar chat agora",
"encerrar chamada agora",
"finalizar atendimento agora",
"terminar conversação agora",
"fechar atendimento agora",
"encerrar atendimento agora",
"desconectar-se agora",
"encerrar interação agora",
"concluir diálogo agora",
"encerrar chat imediatamente",
"terminar sessão agora",
"finalizar conversa agora",
"encerrar interação imediatamente",
"concluir atendimento agora",
"terminar ação agora",
"fechar chat agora",
"despedir-se agora",
"cancelar pedido agora",
"encerrar conexão agora",
"parar imediatamente",
"parar interação agora",
"sair de vez agora",
"cancelar operação agora",
"encerrar discussão agora",
"encerrar interação agora",
"finalizar interação agora",
"desligar agora",
"encerrar chat agora",
"terminar chat agora",
"encerrar chamada agora",
"finalizar atendimento agora",
"terminar conversação agora",
"fechar atendimento agora",
"encerrar atendimento agora",
"desconectar-se agora",
"encerrar interação agora",
"concluir diálogo agora",
"encerrar chat imediatamente",
"terminar sessão agora",
"finalizar conversa agora",
"encerrar interação imediatamente",
"concluir atendimento agora",
"terminar ação agora",
"fechar chat agora",
"despedir-se agora",
"cancelar pedido agora",
"encerrar conexão agora",
"parar imediatamente",
"parar interação agora",
"sair de vez agora",
"cancelar operação agora",
"encerrar discussão agora",
"encerrar interação agora",
"finalizar interação agora",
"desligar agora",
"encerrar chat agora",
"terminar chat agora",
"encerrar chamada agora",
"finalizar atendimento agora",
"terminar conversação agora",
"fechar atendimento agora",
"encerrar atendimento agora",
"desconectar-se agora",
"encerrar interação agora",
"concluir diálogo agora",
"encerrar chat imediatamente",
"terminar sessão agora",
"finalizar conversa agora",
"encerrar interação imediatamente",
"concluir atendimento agora",
"terminar ação agora",
"fechar chat agora",
"despedir-se agora",
"cancelar pedido agora",
"encerrar conexão agora",
"parar imediatamente",
"parar interação agora",
"sair de vez agora",
"cancelar operação agora",
"encerrar discussão agora",
"encerrar interação agora",
"finalizar interação agora",
"desligar agora",
"encerrar chat agora",
"terminar chat agora",
"encerrar chamada agora",
"finalizar atendimento agora",
"terminar conversação agora",
"fechar atendimento agora",
"encerrar atendimento agora",
"desconectar-se agora",
"encerrar interação agora",
"concluir diálogo agora",
"encerrar chat imediatamente",
"terminar sessão agora",
"finalizar conversa agora",
"encerrar interação imediatamente",
"concluir atendimento agora",
"terminar ação agora",
"fechar chat agora",
"despedir-se agora",
"cancelar pedido agora",
"encerrar conexão agora",
"parar imediatamente",
"parar interação agora",
"sair de vez agora",
"cancelar operação agora",
"encerrar discussão agora",
"encerrar interação agora",
"finalizar interação agora",
"desligar agora",
"encerrar chat agora",
"terminar chat agora",
"encerrar chamada agora",
"finalizar atendimento agora",
"terminar conversação agora",
"fechar atendimento agora",
"encerrar atendimento agora",
"desconectar-se agora",
"encerrar interação agora",
"concluir diálogo agora",
"encerrar chat imediatamente",
"terminar sessão agora",
"finalizar conversa agora",
"encerrar interação imediatamente",
"concluir atendimento agora",
"terminar ação agora",
"fechar chat agora",
"despedir-se agora",
"cancelar pedido agora",
"encerrar conexão agora",
"parar imediatamente",
"parar interação agora",
"sair de vez agora",
"cancelar operação agora",
"encerrar discussão agora",
"encerrar interação agora",
"finalizar interação agora",
"desligar agora",
"encerrar chat agora",
"terminar chat agora",
"encerrar chamada agora",
"finalizar atendimento agora",
"terminar conversação agora",
"fechar atendimento agora",
"encerrar atendimento agora",
"desconectar-se agora",
"encerrar interação agora",
"concluir diálogo agora",
"encerrar chat imediatamente",
"terminar sessão agora",
"finalizar conversa agora",
"encerrar interação imediatamente",
"concluir atendimento agora",
"terminar ação agora",
"fechar chat agora",
"despedir-se agora",
"cancelar pedido agora",
"encerrar conexão agora",
"parar imediatamente",
"parar interação agora",
"sair de vez agora",
"cancelar operação agora",
"encerrar discussão agora",
"encerrar interação agora",
"finalizar interação agora",
"desligar agora",
"encerrar chat agora",
"terminar chat agora",
"encerrar chamada agora",
"finalizar atendimento agora",
"terminar conversação agora",
"fechar atendimento agora",
"encerrar atendimento agora",
"desconectar-se agora",
"encerrar interação agora",
"concluir diálogo agora",
"encerrar chat imediatamente",
"terminar sessão agora",
"finalizar conversa agora",
"encerrar interação imediatamente",
"concluir atendimento agora",
"terminar ação agora",
"fechar chat agora",
"despedir-se agora",
"cancelar pedido agora",
"encerrar conexão agora",
"parar imediatamente",
"parar interação agora",
"sair de vez agora",
"cancelar operação agora",
"encerrar discussão agora",
"encerrar interação agora",
"finalizar interação agora",
"desligar agora",
"encerrar chat agora",
"terminar chat agora",
"encerrar chamada agora",
"finalizar atendimento agora",
"terminar conversação agora",
"fechar atendimento agora",
"encerrar atendimento agora",
"desconectar-se agora",
"encerrar interação agora",
"concluir diálogo agora",
"encerrar chat imediatamente",
"terminar sessão agora",
"finalizar conversa agora",
"encerrar interação imediatamente",
"concluir atendimento agora",
"terminar ação agora",
"fechar chat agora",
"despedir-se agora",
"cancelar pedido agora",
"encerrar conexão agora",
"parar imediatamente",
"parar interação agora",
"sair de vez agora",
"cancelar operação agora",
"encerrar discussão agora",
"encerrar interação agora",
"finalizar interação agora",
"desligar agora",
"encerrar chat agora",
"terminar chat agora",
"encerrar chamada agora",
"finalizar atendimento agora",
"terminar conversação agora",
"fechar atendimento agora",
"encerrar atendimento agora",
"desconectar-se agora",
"encerrar interação agora",
"concluir diálogo agora",
"encerrar chat imediatamente",
"terminar sessão agora",
"finalizar conversa agora",
"encerrar interação imediatamente",
"concluir atendimento agora",
"terminar ação agora",
"fechar chat agora",
"despedir-se agora",
"cancelar pedido agora",
"encerrar conexão agora",
"parar imediatamente",
"parar interação agora",
"sair de vez agora",
"cancelar operação agora",
"encerrar discussão agora",
"encerrar interação agora",
"finalizar interação agora",
"desligar agora",
"encerrar chat agora",
"terminar chat agora",
"encerrar chamada agora",
"finalizar atendimento agora",
"terminar conversação agora",
"fechar atendimento agora",
"encerrar atendimento agora",
"desconectar-se agora",
"encerrar interação agora",
"concluir diálogo agora",
"encerrar chat imediatamente",
"terminar sessão agora",
"finalizar conversa agora",
"encerrar interação imediatamente",
"concluir atendimento agora",
"terminar ação agora",
"fechar chat agora",
"despedir-se agora",
"cancelar pedido agora",
"encerrar conexão agora",
"parar imediatamente",
"parar interação agora",
"sair de vez agora",
"cancelar operação agora",
"encerrar discussão agora",
"encerrar interação agora",
"finalizar interação agora",
"desligar agora",
"encerrar chat agora",
"terminar chat agora",
"encerrar chamada agora",
"finalizar atendimento agora",
"terminar conversação agora",
"fechar atendimento agora",
"encerrar atendimento agora",
"desconectar-se agora",
"encerrar interação agora",
"concluir diálogo agora",
"encerrar chat imediatamente",
"terminar sessão agora",
"finalizar conversa agora",
"encerrar interação imediatamente",
"concluir atendimento agora",
"terminar ação agora",
"fechar chat agora",
"despedir-se agora",
"cancelar pedido agora",
"encerrar conexão agora",
"parar imediatamente",
"parar interação agora",
"sair de vez agora",
"cancelar operação agora",
"encerrar discussão agora",
"encerrar interação agora",
"finalizar interação agora",
"desligar agora",
"encerrar chat agora",
"terminar chat agora",
"encerrar chamada agora",
"finalizar atendimento agora",
"terminar conversação agora",
"fechar atendimento agora",
"encerrar atendimento agora",
"desconectar-se agora",
"encerrar interação agora",
"concluir diálogo agora",
"encerrar chat imediatamente",
"terminar sessão agora",
"finalizar conversa agora",
"encerrar interação imediatamente",
"concluir atendimento agora",
"terminar ação agora",
"fechar chat agora",
"despedir-se agora",
"cancelar pedido agora",
"encerrar conexão agora",
"parar imediatamente",
"parar interação agora",
"sair de vez agora",
"cancelar operação agora",
"encerrar discussão agora",
"encerrar interação agora",
"finalizar interação agora",
"desligar agora",
"encerrar chat agora",
"terminar chat agora",
"encerrar chamada agora",
"finalizar atendimento agora",
"terminar conversação agora",
"fechar atendimento agora",
"encerrar atendimento agora",
"desconectar-se agora",
"encerrar interação agora",
"concluir diálogo agora",
"encerrar chat imediatamente",
"terminar sessão agora",
"finalizar conversa agora",
"encerrar interação imediatamente",
"concluir atendimento agora",
"terminar ação agora",
"fechar chat agora",
"despedir-se agora",
"cancelar pedido agora",
"encerrar conexão agora",
"parar imediatamente",
"parar interação agora",
"sair de vez agora",
"cancelar operação agora",
"encerrar discussão agora",
"encerrar interação agora",
"finalizar interação agora",
"desligar agora",
"encerrar chat agora",
"terminar chat agora",
"encerrar chamada agora",
"finalizar atendimento agora",
"terminar conversação agora",
"fechar atendimento agora",
"encerrar atendimento agora",
"desconectar-se agora",
"encerrar interação agora",
"concluir diálogo agora",
"encerrar chat imediatamente",
"terminar sessão agora",
"finalizar conversa agora",
"encerrar interação imediatamente",
"concluir atendimento agora",
"terminar ação agora",
"fechar chat agora",
"despedir-se agora",
"cancelar pedido agora",
"encerrar conexão agora",
"parar imediatamente",
"parar interação agora",
"sair de vez agora",
"cancelar operação agora",
"encerrar discussão agora",
"encerrar interação agora",
"finalizar interação agora",
"desligar agora",
"encerrar chat agora",
"terminar chat agora",
"encerrar chamada agora",
"finalizar atendimento agora",
"terminar conversação agora",
"fechar atendimento agora",
"encerrar atendimento agora",
"desconectar-se agora",
"encerrar interação agora",
"concluir diálogo agora",
"encerrar chat imediatamente",
"terminar sessão agora",
"finalizar conversa agora",
"encerrar interação imediatamente",
"concluir atendimento agora",
"terminar ação agora",
"fechar chat agora",
"despedir-se agora",
"cancelar pedido agora",
"encerrar conexão agora",
"parar imediatamente",
"parar interação agora",
"sair de vez agora",
"cancelar operação agora",
"encerrar discussão agora",
"encerrar interação agora",
"finalizar interação agora",
"desligar agora",
"encerrar chat agora",
"terminar chat agora",
"encerrar chamada agora",
"finalizar atendimento agora",
"terminar conversação agora",
"fechar atendimento agora",
"encerrar atendimento agora",
"desconectar-se agora",
"encerrar interação agora",
"concluir diálogo agora",
"encerrar chat imediatamente",
"terminar sessão agora",
"finalizar conversa agora",
"encerrar interação imediatamente",
"concluir atendimento agora",
"terminar ação agora",
"fechar chat agora",
"despedir-se agora",
"cancelar pedido agora",
"encerrar conexão agora",
"parar imediatamente",
"parar interação agora",
"sair de vez agora",
"cancelar operação agora",
"encerrar discussão agora",
"encerrar interação agora",
"finalizar interação agora",
"desligar agora",
"encerrar chat agora",
"terminar chat agora",
"encerrar chamada agora",
"finalizar atendimento agora",
"terminar conversação agora",
"fechar atendimento agora",
"encerrar atendimento agora",
"desconectar-se agora",
"encerrar interação agora",
"concluir diálogo agora",
"encerrar chat imediatamente",
"terminar sessão agora",
"finalizar conversa agora",
"encerrar interação imediatamente",
"concluir atendimento agora",
"terminar ação agora",
"fechar chat agora",
"despedir-se agora",
"cancelar pedido agora",
"encerrar conexão agora",
"parar imediatamente",
"parar interação agora",
"sair de vez agora",
"cancelar operação agora",
"encerrar discussão agora",
"encerrar interação agora",
"finalizar interação agora",
"desligar agora",
"encerrar chat agora",
"terminar chat agora",
"encerrar chamada agora",
"finalizar atendimento agora",
"terminar conversação agora",
"fechar atendimento agora",
"encerrar atendimento agora",
"desconectar-se agora",
"encerrar interação agora",
"concluir diálogo agora",
"encerrar chat imediatamente",
"terminar sessão agora",
"finalizar conversa agora",
"encerrar interação imediatamente",
"concluir atendimento agora",
"terminar ação agora",
"fechar chat agora",
"despedir-se agora",
"cancelar pedido agora",
"encerrar conexão agora",
"parar imediatamente",
"parar interação agora",
"sair de vez agora",
"cancelar operação agora",
"encerrar discussão agora",
"encerrar interação agora",
"finalizar interação agora",
"desligar agora",
"encerrar chat agora",
"terminar chat agora",
"encerrar chamada agora",
"finalizar atendimento agora",
"terminar conversação agora",
"fechar atendimento agora",
"encerrar atendimento agora",
"desconectar-se agora",
"encerrar interação agora",
"concluir diálogo agora",
"encerrar chat imediatamente",
"terminar sessão agora",
"finalizar conversa agora",
"encerrar interação imediatamente",
"concluir atendimento agora",
"terminar ação agora",
"fechar chat agora",
"despedir-se agora",
"cancelar pedido agora",
"encerrar conexão agora",
"parar imediatamente",
"parar interação agora",
"sair de vez agora",
"cancelar operação agora",
"encerrar discussão agora",
"encerrar interação agora",
"finalizar interação agora",
"desligar agora",
"encerrar chat agora",
"terminar chat agora",
"encerrar chamada agora",
"finalizar atendimento agora",
"terminar conversação agora",
"fechar atendimento agora",
"encerrar atendimento agora",
"desconectar-se agora",
"encerrar interação agora",
"concluir diálogo agora",
"encerrar chat imediatamente",
"terminar sessão agora",
"finalizar conversa agora",
"encerrar interação imediatamente",
"concluir atendimento agora",
"terminar ação agora",
"fechar chat agora",
"despedir-se agora",
"cancelar pedido agora",
"encerrar conexão agora",
"parar imediatamente",
"parar interação agora",
"sair de vez agora",
"cancelar operação agora",
"encerrar discussão agora",
"encerrar interação agora",
"finalizar interação agora",
"desligar agora",
"encerrar chat agora",
"terminar chat agora",
"encerrar chamada agora",
"finalizar atendimento agora",
"terminar conversação agora",
"fechar atendimento agora",
"encerrar atendimento agora",
"desconectar-se agora",
"encerrar interação agora",
"concluir diálogo agora",
"encerrar chat imediatamente",
"terminar sessão agora",
"finalizar conversa agora",
"encerrar interação imediatamente",
"concluir atendimento agora",
"terminar ação agora",
"fechar chat agora",
"despedir-se agora",
"cancelar pedido agora",
"encerrar conexão agora",
"parar imediatamente",
"parar interação agora",
"sair de vez agora",
"cancelar operação agora",
"encerrar discussão agora",
"encerrar interação agora",
"finalizar interação agora",
"desligar agora",
"encerrar chat agora",
"terminar chat agora",
"encerrar chamada agora",
"finalizar atendimento agora",
"terminar conversação agora",
"fechar atendimento agora",
"encerrar atendimento agora",
"desconectar-se agora",
"encerrar interação agora",
"concluir diálogo agora",
"encerrar chat imediatamente",
"terminar sessão agora",
"finalizar conversa agora",
"encerrar interação imediatamente",
"concluir atendimento agora",
"terminar ação agora",
"fechar chat agora",
"despedir-se agora",
"cancelar pedido agora",
"encerrar conexão agora",
"parar imediatamente",
"parar interação agora",
"sair de vez agora",
"cancelar operação agora",
"encerrar discussão agora",
"encerrar interação agora",
"finalizar interação agora",
"desligar agora",
"encerrar chat agora",
"terminar chat agora",
"encerrar chamada agora",
"finalizar atendimento agora",
"terminar conversação agora",
"fechar atendimento agora",
"encerrar atendimento agora",
"desconectar-se agora",
"encerrar interação agora",
"concluir diálogo agora",
"encerrar chat imediatamente",
"terminar sessão agora",
"finalizar conversa agora",
"encerrar interação imediatamente",
"concluir atendimento agora",
"terminar ação agora",
"fechar chat agora",
"despedir-se agora",
"cancelar pedido agora",
"encerrar conexão agora",
"parar imediatamente",
"parar interação agora",
"sair de vez agora",
"cancelar operação agora",
"encerrar discussão agora",
"encerrar interação agora",
"finalizar interação agora",
"desligar agora",
"encerrar chat agora",
"terminar chat agora",
"encerrar chamada agora",
"finalizar atendimento agora",
"terminar conversação agora",
"fechar atendimento agora",
"encerrar atendimento agora",
"desconectar-se agora",
"encerrar interação agora",
"concluir diálogo agora",
"encerrar chat imediatamente",
"terminar sessão agora",
"finalizar conversa agora",
"encerrar interação imediatamente",
"concluir atendimento agora",
"terminar ação agora",
"fechar chat agora",
"despedir-se agora",
"cancelar pedido agora",
"encerrar conexão agora",
"parar imediatamente",
"parar interação agora",
"sair de vez agora",
"cancelar operação agora",
"encerrar discussão agora",
"encerrar interação agora",
"finalizar interação agora",
"desligar agora",
"encerrar chat agora",
"terminar chat agora",
"encerrar chamada agora",
"finalizar atendimento agora",
"terminar conversação agora",
"fechar atendimento agora",
"encerrar atendimento agora",
"desconectar-se agora",
"encerrar interação agora",
"concluir diálogo agora",
"encerrar chat imediatamente",
"terminar sessão agora",
"finalizar conversa agora",
"encerrar interação imediatamente",
"concluir atendimento agora",
"terminar ação agora",
"fechar chat agora",
"despedir-se agora",
"cancelar pedido agora",
"encerrar conexão agora",
"parar imediatamente",
"parar interação agora",
"sair de vez agora",
"cancelar operação agora",
"encerrar discussão agora",
"encerrar interação agora",
"finalizar interação agora",
"desligar agora",
"encerrar chat agora",
"terminar chat agora",
"encerrar chamada agora",
"finalizar atendimento agora",
"terminar conversação agora",
"fechar atendimento agora",
"encerrar atendimento agora",
"desconectar-se agora",
"encerrar interação agora",
"concluir diálogo agora",
"encerrar chat imediatamente",
"terminar sessão agora"
];

// Exporte as listas para uso em outros arquivos usando CommonJS
module.exports = {
  registrar,
  naoRegistrar,
  consultas,
  greetings,
  verConsultas,
  confirmar,
  naoMarcar,
  encerrar,
};
