//array inicial
const greetings = [
  "oi",
  "ola",
  "oi tudo bem",
  "bom dia",
  "boa tarde",
  "boa noite",
  "Oi, bom dia",
  "Oi, boa tarde",
  "Oi, boa noite",
  "Oi!",
  "Oi.",
  "Oi, tudo bem?",
  "olá",
  "E aí?",
  "Oi, como vai?",
  "Olá, tudo bem?",
  "Olá, boa tarde",
  "E aí, tudo tranquilo?",
  "Bom dia!",
  "Boa tarde!",
  "Boa noite!",
  "Oi, bom dia!",
  "Oi, boa tarde!",
  "Oi, boa noite!",
  "Como está?",
  "Tudo bem contigo?",
  "Oi, como você está?",
  "Oi, como vai você?",
  "E aí, como está?",
  "Olá, como vai?",
  "Ei!",
  "Oi, tem alguém aí?",
  "Olaaa",
  "Ooiii",
  "Oláááá",
  "Bão dia",
  "Bããão dia",
  "Oiiee",
  "Boa tardii",
  "Buon giorno",
  "Opa, tudo jóiaaa?",
  "Tudu bom?",
  "Ei, tdo bom aí?",
  "Tdo ótimo!",
  "Tudibãão?",
  "Ei, tudo bem consigo?",
  "Bão, diia!",
  "Tdo show?",
  "Tudo bem, e aí contigo?",
  "Oi, como vái?",
  "Oláá, como tá tuuudo?",
  "Boa tardee, td belê?",
  "Oi, como vc tá?",
  "Eaí, td bem ctg?",
  "Oii, tudo bãão?",
  "Oiêêê",
  "Oláa, como estás?",
  "Tudo ótímo, e vc?",
  "Bão díaa!",
  "Ei, tudo jóinha?",
  "Tudibão, e contigo?",
  "Oi, tudo bemm?",
  "Olá, como vai tds?",
  "Bom diaaa, como tá?",
  "Eaí, td belezaa?",
  "Oii, como está a viida?",
  "Olá, tudo legau?",
  "Boa tardee, tudo certin?",
  "Ei, como você estás?",
  "Tudo bem consigo?",
  "Tudibãão, e tu?",
  "Oiêê, tudo jóia?",
  "Oláa, tudo ótimo?",
  "Bom dia, como estái?",
  "Eaí, tudo belezaa?",
  "Oii, como você tá?",
  "Olá, tudo em pé?",
  "Boa tarde, e aí cê tá?",
  "Oi, tudo joiaa?",
  "Ei, tudo belezinha?",
  "Tudo de boa, e contigo?",
  "Tudibão, e você?",
  "Oiêê, como tá o clima?",
  "Oláa, tudo certo aí?",
  "Bom diaa, tudo bemm?",
  "Eaí, tudo tranquilo?",
  "Oii, como você vai?",
  "Olá, tudo em ordem?",
  "Boa tarde, e aí tudo jóia?",
  "Oi, tudo na paz?",
  "Ei, tudo suave?",
  "Tudo de boa, e contigo?",
  "oi",
  "olá",
  "ola",
  "e aí",
  "tudo bem?",
  "como vai?",
  "bom dia",
  "boa tarde",
  "boa noite",
  "saudações",
  "olá amigo",
  "oi tudo bem?",
  "olá, como vai?",
  "oi, tudo tranquilo?",
  "oi pessoal",
  "e aí galera?",
  "tudo joia?",
  "oi pessoal, tudo bem?",
  "olá a todos",
  "olá pessoal",
  "como estão?",
  "bom dia a todos",
  "boa tarde amigos",
  "boa noite pessoal",
  "saudações a todos",
  "e aí pessoal, tudo bem?",
  "tudo beleza?",
  "como é que é?",
  "e aí, como estão?",
  "oi, tudo em paz?",
  "olá pessoal, tudo tranquilo?",
  "oi, como vai a vida?",
  "oi galera, tudo certo?",
  "e aí pessoal, como estão?",
  "tudo bom com vocês?",
  "olá pessoal, tudo bem por aí?",
  "oi, como você está?",
  "olá amigos, como vai isso?",
  "e aí, como anda a vida?",
  "e aí pessoal, tudo na paz?",
  "bom dia pessoal, tudo bem?",
  "oi pessoal, tudo em ordem?",
  "olá, tudo bem por aí?",
  "e aí, tudo em cima?",
  "tudo legal?",
  "e aí, como é que está?",
  "oi, como você está hoje?",
  "olá pessoal, tudo nos conformes?",
  "tudo tranquilo por aí?",
  "e aí pessoal, tudo certinho?",
  "bom dia pessoal, como vão as coisas?",
  "oi pessoal, tudo ok?",
  "olá, tudo de boa?",
  "e aí, tudo beleza?",
  "tudo em paz?",
  "oi, como você está se sentindo?",
  "olá amigos, tudo tranquilo?",
  "e aí, como vai o dia?",
  "oi pessoal, tudo na tranquilidade?",
  "olá, como estão todos?",
  "e aí, tudo bem contigo?",
  "tudo certo por aí?",
  "oi, como estão as coisas?",
  "olá pessoal, como vai a luta?",
  "e aí pessoal, tudo em ordem?",
  "bom dia a todos, como estão?",
  "oi pessoal, como vai o dia?",
  "olá, como vai essa força?",
  "e aí, como vai essa maré?",
  "tudo bem contigo?",
  "oi, como vai a vida?",
  "olá pessoal, tudo em paz?",
  "e aí, tudo joia?",
  "tudo tranquilo por aí?",
  "oi pessoal, como estão as coisas?",
  "olá, como você está se sentindo?",
  "e aí, como vai a jornada?",
  "tudo bem por aí?",
  "oi, como está o seu dia?",
  "olá amigos, como vai a rotina?",
  "e aí pessoal, tudo de boa?",
  "tudo em ordem?",
  "oi, como está a vibe?",
  "olá pessoal, como estão os ânimos?",
  "e aí, como estão os trabalhos?",
  "tudo na paz?",
  "oi pessoal, como vão os afazeres?",
  "olá, como vai essa energia?",
  "e aí, como vai o andamento?",
  "tudo beleza por aí?",
  "oi, como está a disposição?",
  "olá pessoal, como estão os projetos?",
  "e aí, como vai o clima?",
  "tudo em cima?",
  "oi pessoal, como estão as novidades?",
  "olá, como vai a inspiração?",
  "Ei",
  "Hei",
  "Ola",
  "Oie",
  "Oii",
  "Tudobem?",
  "Tudobm?",
  "Td bem?",
  "Tudoben?",
  "Tudob?",
  "Tdo bem?",
  "Tudobem?",
  "Tudobem?",
  "Td bem?",
  "Tbem?",
  "Oioi",
  "Olá, tudo bem?",
  "Oi, como vai?",
  "Bom diaaa!",
  "Boa tardeee!",
  "Boa noitiiii!",
  "Saudaçoes",
  "Eae",
  "Ola, como vai?",
  "Ola, tudo bem?",
  "Olá, tudo bom?",
  "Olá, como tá?",
  "Tudo bele?",
  "Tdo bem?",
  "Td bom?",
  "Tdo bein?",
  "Olaa",
  "Tudo belê?",
  "Oiaí",
  "Boa tardi",
  "Boa noiche",
  "Tudo bm?",
  "Bom diaa!",
  "Bnoite!",
  "Boa tardee!",
  "Bom diaa!",
  "Bom diia!",
  "Tuduu bom?",
  "Tudo bm?",
  "Eai, tudo beleza?",
  "Tudo belezaa?",
  "Tudo bom, eai?",
  "Tudo jóia?",
  "Opa, beleza?",
  "Opa, eai?",
  "Opa, tdo bem?",
  "Oiai, tudo joia?",
  "oieee",
  "salve quebrada",
  "eae mano, blz?",
  "eae mano blz",
  "suave?",
];

  const removerPedido = [
    "quero remover um item",
    "remover pedido",
    "remover item",
    "tirar um lanche",
    "tirar a bebida",
    "tirar o suco",
    "tirar batata",
    "tirar esse",
    "cancelar pedido",
    "cancelar item",
    "não quero mais esse",
    "não quero mais",
    "desfazer pedido",
    "desfaz esse pedido",
    "excluir item",
    "excluir pedido",
    "apaga esse pedido",
    "apagar pedido",
    "apaga esse item",
    "retira esse",
    "retirar pedido",
    "retirar item",
    "não quero esse lanche",
    "não quero esse item",
    "não quero refrigerante",
    "não quero suco",
    "não quero batata",
    "não quero mais o pedido",
    "não desejo mais isso",
    "tira isso",
    "tira",
    "cancela isso",
    "remove esse item",
    "remove",
    "não, tira isso",
    "não, apaga",
    "não, cancela",
    "não, exclui",
    "não quero mais esse lanche",
    "não quero mais esse item",
    "não, não quero mais esse pedido",
    "não, desfaz",
    "não, retira",
    "não, exclui esse",
    "não, cancela isso",
    "não, já mudei de ideia",
    "não, não quero isso agora",
    "não, não quero esse combo",
    "não, já pedi errado",
    "não, esse não",
    "não, sai esse",
    "não, retira esse lanche",
    "não, cancela o que pedi",
    "não, apaga tudo",
    "não, refazer pedido",
    "não quero mais isso",
    "não quero mais esse combo",
    "não quero esse pedido",
    "não quero esse combo",
    "não, já desisti",
    "não, me arrependi",
  
];

//marcar consulta
const pedidos = [
  "lanche", "hambúrguer", "batata", "refrigerante", "suco",
  "água", "coca-cola", "budweiser", "heinekein",
  "dogão", "salgado de salsicha", "coxinha", "salgado de calabresa",
  "boa", "brahma", "stella", "salgadinho",

  "uma coxinha", "duas coxinhas", "três coxinhas", "quatro coxinhas", "cinco coxinhas", "seis coxinhas", "sete coxinhas", "oito coxinhas", "nove coxinhas", "dez coxinhas",
  "uma batata", "duas batatas", "três batatas", "quatro batatas", "cinco batatas", "seis batatas", "sete batatas", "oito batatas", "nove batatas", "dez batatas",
  "um hambúrguer", "dois hambúrgueres", "três hambúrgueres", "quatro hambúrgueres", "cinco hambúrgueres", "seis hambúrgueres", "sete hambúrgueres", "oito hambúrgueres", "nove hambúrgueres", "dez hambúrgueres",
  "um refrigerante", "dois refrigerantes", "três refrigerantes", "quatro refrigerantes", "cinco refrigerantes", "seis refrigerantes", "sete refrigerantes", "oito refrigerantes", "nove refrigerantes", "dez refrigerantes",
  "um suco", "dois sucos", "três sucos", "quatro sucos", "cinco sucos", "seis sucos", "sete sucos", "oito sucos", "nove sucos", "dez sucos",
  "uma água", "duas águas", "três águas", "quatro águas", "cinco águas", "seis águas", "sete águas", "oito águas", "nove águas", "dez águas",
  "uma coca-cola", "duas coca-colas", "três coca-colas", "quatro coca-colas", "cinco coca-colas", "seis coca-colas", "sete coca-colas", "oito coca-colas", "nove coca-colas", "dez coca-colas",
  "uma budweiser", "duas budweisers", "três budweisers", "quatro budweisers", "cinco budweisers", "seis budweisers", "sete budweisers", "oito budweisers", "nove budweisers", "dez budweisers",
  "uma heinekein", "duas heinekeins", "três heinekeins", "quatro heinekeins", "cinco heinekeins", "seis heinekeins", "sete heinekeins", "oito heinekeins", "nove heinekeins", "dez heinekeins",
  "um dogão", "dois dogões", "três dogões", "quatro dogões", "cinco dogões", "seis dogões", "sete dogões", "oito dogões", "nove dogões", "dez dogões",
  "um salgado de salsicha", "dois salgados de salsicha", "três salgados de salsicha", "quatro salgados de salsicha", "cinco salgados de salsicha", "seis salgados de salsicha", "sete salgados de salsicha", "oito salgados de salsicha", "nove salgados de salsicha", "dez salgados de salsicha",
  "um salgado de calabresa", "dois salgados de calabresa", "três salgados de calabresa", "quatro salgados de calabresa", "cinco salgados de calabresa", "seis salgados de calabresa", "sete salgados de calabresa", "oito salgados de calabresa", "nove salgados de calabresa", "dez salgados de calabresa",
  "uma boa", "duas boas", "três boas", "quatro boas", "cinco boas", "seis boas", "sete boas", "oito boas", "nove boas", "dez boas",
  "uma brahma", "duas brahmas", "três brahmas", "quatro brahmas", "cinco brahmas", "seis brahmas", "sete brahmas", "oito brahmas", "nove brahmas", "dez brahmas",
  "uma stella", "duas stellas", "três stellas", "quatro stellas", "cinco stellas", "seis stellas", "sete stellas", "oito stellas", "nove stellas", "dez stellas",
  "um salgadinho", "dois salgadinhos", "três salgadinhos", "quatro salgadinhos", "cinco salgadinhos", "seis salgadinhos", "sete salgadinhos", "oito salgadinhos", "nove salgadinhos", "dez salgadinhos"
];
//ver consulta
const verPedido = [
"ver",
"quero ver um pedido",
"quero ver meus pedidos",
"quero ver",
"liste para mim",
"lista",
"pedidos",
"meus pedidos",
"pedido",
"consult",
"agendados",
"ver meus pedidos",
"quero ver",
"mostrar",
"ver pedido",
"marcado",
"visualizar",
"verificar",
"exibir",
"verificar pedidos",
"verificar compromissos",
"verificar agendamentos",
"verificar horários",
"mostrar pedidos",
"mostrar agendamentos",
"ver histórico de pedidos",
"consultar histórico",
"verificar pedidos marcados",
"mostrar pedidos agendados",
"ver pedidos pendentes",
"ver pedidos confirmados",
"ver minhas marcações",
"ver meus agendamentos",
"ver minhas reservas",
"marcados",
"ver pedidos",
"quer ver quais pedidos eu tenho",
"quer ver",
"vão ve",
"vao ve"
];

//confirmar a consulta => sim
const confirmarPedido = [
  "confirmar",
  "confirmae",
  "confirma",
  "pode pa",
  "vai logo",
  "bora mano",
  "lets go",
  "s",
  "sim",
  "marcar",
  "sim, confirmar",
  "sim, marcar",
  "confirmo",
  "confirmado",
  "sim, por favor",
  "sim, claro",
  "ok",
  "tudo certo",
  "certo",
  "confirmado com sucesso",
  "fechar",
  "concluir",
  "validar",
  "aceitar",
  "agende",
  "marque",
  "sim, quero",
  "sim, desejo",
  "marque para mim",
  "marque agora",
  "desejo confirmar",
  "quero confirmar",
  "gostaria de confirmar",
  "quero marcar",
  "gostaria de marcar",
  "desejo marcar",
  "quero confirmar agora",
  "gostaria de confirmar agora",
  "desejo confirmar agora",
  "gostaria de marcar agora",
  "desejo marcar agora",
];

const encerrar = [
"obrigado",
"obg",
"ok, obrigado",
"preciso que encerre",
"quero encerrar",
"chega",
"flw",
"ok obrigado",
"okay",
"ok valeu",
"ok meu irmao",
"ok, obg",
"ok, perfeito",
"ok, tamo junto",
"ok",
"pode encerrar",
"até mais",
"valeu",
"tamo junto",
"tmj",
"encerrar",
"terminar",
"finalizar",
"fechar",
"sair",
"cancelar atendimento",
"parar",
"adeus",
"até logo",
"sair do chat",
"sair da conversa",
"desligar",
"encerrar chat",
"encerrar conversa",
"adeus",
"fim",
"cancelar operação",
"voltar mais tarde",
"cancelar ação",
"sair agora",
"concluir",
"despedir",
"deixar",
"sair do sistema",
"terminar sessão",
"encerrar aplicativo",
"voltar ao menu principal",
"cancelar tudo",
"desconectar",
"voltar mais tarde",
"não quero mais",
"cancelar",
"sair daqui",
"dizer tchau",
"quero encerrar",
"quero desligar",
"quero sair",
"desisti",
"sai pra la",
"me enganei",
"obrigada",
"valeu mesmo",
"vlw",
"tmj",
"tchauzinho",
"falou",
"obrigado por tudo",
"beijos",
"até breve",
"até logo",
"volte sempre",
"até a próxima",
"grato",
"sair do sistema",
"encerrar sessão",
"voltar ao início",
"cancelar processo",
"terminar conversa",
"finalizar chat",
"desconectar-se",
"sair agora mesmo",
"encerrar interação",
"concluir operação",
"terminar atendimento",
"finalizar ação",
"fechar janela",
"encerrar conversação",
"interromper",
"parar agora",
"parar conversa",
"sair definitivamente",
"cancelar solicitação",
"encerrar diálogo",
"encerrar comunicação",
"encerrar interação",
"finalizar sessão",
"voltar ao ponto inicial",
"cancelar processo",
"terminar diálogo",
"finalizar comunicação",
"desconectar-se",
"sair imediatamente",
"encerrar interação",
"concluir atendimento",
"terminar ação",
"fechar chat",
"despedir-se",
"cancelar pedido",
"encerrar conexão",
"parar imediatamente",
"parar interação",
"sair de vez",
"cancelar operação",
"encerrar discussão",
"encerrar interação",
"finalizar interação",
"desligar agora",
"encerrar chat agora",
"terminar chat",
"encerrar chamada",
"finalizar atendimento",
"terminar conversação",
"fechar atendimento",
"encerrar atendimento",
"desconectar-se agora",
"encerrar interação agora",
"concluir diálogo",
"encerrar chat imediatamente",
"terminar sessão agora",
"finalizar conversa agora",
"encerrar interação imediatamente",
"concluir atendimento agora",
"terminar ação agora",
"fechar chat agora",
"despedir-se agora",
"cancelar pedido agora",
"encerrar conexão agora",
"parar imediatamente",
"parar interação agora",
"sair de vez agora",
"cancelar operação agora",
"encerrar discussão agora",
"encerrar interação agora",
"finalizar interação agora",
"desligar agora",
"encerrar chat agora",
"terminar chat agora",
"encerrar chamada agora",
"finalizar atendimento agora",
"terminar conversação agora",
"fechar atendimento agora",
"encerrar atendimento agora",
"desconectar-se agora",
"encerrar interação agora",
"concluir diálogo agora",
"encerrar chat imediatamente",
"terminar sessão agora",
"finalizar conversa agora",
"encerrar interação imediatamente",
"concluir atendimento agora",
"terminar ação agora",
"fechar chat agora",
"despedir-se agora",
"cancelar pedido agora",
"encerrar conexão agora",
"parar imediatamente",
"parar interação agora",
"sair de vez agora",
"cancelar operação agora",
"encerrar discussão agora",
"encerrar interação agora",
"finalizar interação agora",
"desligar agora",
"encerrar chat agora",
"terminar chat agora",
"encerrar chamada agora",
"finalizar atendimento agora",
"terminar conversação agora",
"fechar atendimento agora",
"encerrar atendimento agora",
"desconectar-se agora",
"encerrar interação agora",
"concluir diálogo agora",
"encerrar chat imediatamente",
"terminar sessão agora",
"finalizar conversa agora",
"encerrar interação imediatamente",
"concluir atendimento agora",
"terminar ação agora",
"fechar chat agora",
"despedir-se agora",
"cancelar pedido agora",
"encerrar conexão agora",
"parar imediatamente",
"parar interação agora",
"sair de vez agora",
"cancelar operação agora",
"encerrar discussão agora",
"encerrar interação agora",
"finalizar interação agora",
"desligar agora",
"encerrar chat agora",
"terminar chat agora",
"encerrar chamada agora",
"finalizar atendimento agora",
"terminar conversação agora",
"fechar atendimento agora",
"encerrar atendimento agora",
"desconectar-se agora",
"encerrar interação agora",
"concluir diálogo agora",
"encerrar chat imediatamente",
"terminar sessão agora",
"finalizar conversa agora",
"encerrar interação imediatamente",
"concluir atendimento agora",
"terminar ação agora",
"fechar chat agora",
"despedir-se agora",
"cancelar pedido agora",
"encerrar conexão agora",
"parar imediatamente",
"parar interação agora",
"sair de vez agora",
"cancelar operação agora",
"encerrar discussão agora",
"encerrar interação agora",
"finalizar interação agora",
"desligar agora",
"encerrar chat agora",
"terminar chat agora",
"encerrar chamada agora",
"finalizar atendimento agora",
"terminar conversação agora",
"fechar atendimento agora",
"encerrar atendimento agora",
"desconectar-se agora",
"encerrar interação agora",
"concluir diálogo agora",
"encerrar chat imediatamente",
"terminar sessão agora",
"finalizar conversa agora",
"encerrar interação imediatamente",
"concluir atendimento agora",
"terminar ação agora",
"fechar chat agora",
"despedir-se agora",
"cancelar pedido agora",
"encerrar conexão agora",
"parar imediatamente",
"parar interação agora",
"sair de vez agora",
"cancelar operação agora",
"encerrar discussão agora",
"encerrar interação agora",
"finalizar interação agora",
"desligar agora",
"encerrar chat agora",
"terminar chat agora",
"encerrar chamada agora",
"finalizar atendimento agora",
"terminar conversação agora",
"fechar atendimento agora",
"encerrar atendimento agora",
"desconectar-se agora",
"encerrar interação agora",
"concluir diálogo agora",
"encerrar chat imediatamente",
"terminar sessão agora",
"finalizar conversa agora",
"encerrar interação imediatamente",
"concluir atendimento agora",
"terminar ação agora",
"fechar chat agora",
"despedir-se agora",
"cancelar pedido agora",
"encerrar conexão agora",
"parar imediatamente",
"parar interação agora",
"sair de vez agora",
"cancelar operação agora",
"encerrar discussão agora",
"encerrar interação agora",
"finalizar interação agora",
"desligar agora",
"encerrar chat agora",
"terminar chat agora",
"encerrar chamada agora",
"finalizar atendimento agora",
"terminar conversação agora",
"fechar atendimento agora",
"encerrar atendimento agora",
"desconectar-se agora",
"encerrar interação agora",
"concluir diálogo agora",
"encerrar chat imediatamente",
"terminar sessão agora",
"finalizar conversa agora",
"encerrar interação imediatamente",
"concluir atendimento agora",
"terminar ação agora",
"fechar chat agora",
"despedir-se agora",
"cancelar pedido agora",
"encerrar conexão agora",
"parar imediatamente",
"parar interação agora",
"sair de vez agora",
"cancelar operação agora",
"encerrar discussão agora",
"encerrar interação agora",
"finalizar interação agora",
"desligar agora",
"encerrar chat agora",
"terminar chat agora",
"encerrar chamada agora",
"finalizar atendimento agora",
"terminar conversação agora",
"fechar atendimento agora",
"encerrar atendimento agora",
"desconectar-se agora",
"encerrar interação agora",
"concluir diálogo agora",
"encerrar chat imediatamente",
"terminar sessão agora",
"finalizar conversa agora",
"encerrar interação imediatamente",
"concluir atendimento agora",
"terminar ação agora",
"fechar chat agora",
"despedir-se agora",
"cancelar pedido agora",
"encerrar conexão agora",
"parar imediatamente",
"parar interação agora",
"sair de vez agora",
"cancelar operação agora",
"encerrar discussão agora",
"encerrar interação agora",
"finalizar interação agora",
"desligar agora",
"encerrar chat agora",
"terminar chat agora",
"encerrar chamada agora",
"finalizar atendimento agora",
"terminar conversação agora",
"fechar atendimento agora",
"encerrar atendimento agora",
"desconectar-se agora",
"encerrar interação agora",
"concluir diálogo agora",
"encerrar chat imediatamente",
"terminar sessão agora",
"finalizar conversa agora",
"encerrar interação imediatamente",
"concluir atendimento agora",
"terminar ação agora",
"fechar chat agora",
"despedir-se agora",
"cancelar pedido agora",
"encerrar conexão agora",
"parar imediatamente",
"parar interação agora",
"sair de vez agora",
"cancelar operação agora",
"encerrar discussão agora",
"encerrar interação agora",
"finalizar interação agora",
"desligar agora",
"encerrar chat agora",
"terminar chat agora",
"encerrar chamada agora",
"finalizar atendimento agora",
"terminar conversação agora",
"fechar atendimento agora",
"encerrar atendimento agora",
"desconectar-se agora",
"encerrar interação agora",
"concluir diálogo agora",
"encerrar chat imediatamente",
"terminar sessão agora",
"finalizar conversa agora",
"encerrar interação imediatamente",
"concluir atendimento agora",
"terminar ação agora",
"fechar chat agora",
"despedir-se agora",
"cancelar pedido agora",
"encerrar conexão agora",
"parar imediatamente",
"parar interação agora",
"sair de vez agora",
"cancelar operação agora",
"encerrar discussão agora",
"encerrar interação agora",
"finalizar interação agora",
"desligar agora",
"encerrar chat agora",
"terminar chat agora",
"encerrar chamada agora",
"finalizar atendimento agora",
"terminar conversação agora",
"fechar atendimento agora",
"encerrar atendimento agora",
"desconectar-se agora",
"encerrar interação agora",
"concluir diálogo agora",
"encerrar chat imediatamente",
"terminar sessão agora",
"finalizar conversa agora",
"encerrar interação imediatamente",
"concluir atendimento agora",
"terminar ação agora",
"fechar chat agora",
"despedir-se agora",
"cancelar pedido agora",
"encerrar conexão agora",
"parar imediatamente",
"parar interação agora",
"sair de vez agora",
"cancelar operação agora",
"encerrar discussão agora",
"encerrar interação agora",
"finalizar interação agora",
"desligar agora",
"encerrar chat agora",
"terminar chat agora",
"encerrar chamada agora",
"finalizar atendimento agora",
"terminar conversação agora",
"fechar atendimento agora",
"encerrar atendimento agora",
"desconectar-se agora",
"encerrar interação agora",
"concluir diálogo agora",
"encerrar chat imediatamente",
"terminar sessão agora",
"finalizar conversa agora",
"encerrar interação imediatamente",
"concluir atendimento agora",
"terminar ação agora",
"fechar chat agora",
"despedir-se agora",
"cancelar pedido agora",
"encerrar conexão agora",
"parar imediatamente",
"parar interação agora",
"sair de vez agora",
"cancelar operação agora",
"encerrar discussão agora",
"encerrar interação agora",
"finalizar interação agora",
"desligar agora",
"encerrar chat agora",
"terminar chat agora",
"encerrar chamada agora",
"finalizar atendimento agora",
"terminar conversação agora",
"fechar atendimento agora",
"encerrar atendimento agora",
"desconectar-se agora",
"encerrar interação agora",
"concluir diálogo agora",
"encerrar chat imediatamente",
"terminar sessão agora",
"finalizar conversa agora",
"encerrar interação imediatamente",
"concluir atendimento agora",
"terminar ação agora",
"fechar chat agora",
"despedir-se agora",
"cancelar pedido agora",
"encerrar conexão agora",
"parar imediatamente",
"parar interação agora",
"sair de vez agora",
"cancelar operação agora",
"encerrar discussão agora",
"encerrar interação agora",
"finalizar interação agora",
"desligar agora",
"encerrar chat agora",
"terminar chat agora",
"encerrar chamada agora",
"finalizar atendimento agora",
"terminar conversação agora",
"fechar atendimento agora",
"encerrar atendimento agora",
"desconectar-se agora",
"encerrar interação agora",
"concluir diálogo agora",
"encerrar chat imediatamente",
"terminar sessão agora",
"finalizar conversa agora",
"encerrar interação imediatamente",
"concluir atendimento agora",
"terminar ação agora",
"fechar chat agora",
"despedir-se agora",
"cancelar pedido agora",
"encerrar conexão agora",
"parar imediatamente",
"parar interação agora",
"sair de vez agora",
"cancelar operação agora",
"encerrar discussão agora",
"encerrar interação agora",
"finalizar interação agora",
"desligar agora",
"encerrar chat agora",
"terminar chat agora",
"encerrar chamada agora",
"finalizar atendimento agora",
"terminar conversação agora",
"fechar atendimento agora",
"encerrar atendimento agora",
"desconectar-se agora",
"encerrar interação agora",
"concluir diálogo agora",
"encerrar chat imediatamente",
"terminar sessão agora",
"finalizar conversa agora",
"encerrar interação imediatamente",
"concluir atendimento agora",
"terminar ação agora",
"fechar chat agora",
"despedir-se agora",
"cancelar pedido agora",
"encerrar conexão agora",
"parar imediatamente",
"parar interação agora",
"sair de vez agora",
"cancelar operação agora",
"encerrar discussão agora",
"encerrar interação agora",
"finalizar interação agora",
"desligar agora",
"encerrar chat agora",
"terminar chat agora",
"encerrar chamada agora",
"finalizar atendimento agora",
"terminar conversação agora",
"fechar atendimento agora",
"encerrar atendimento agora",
"desconectar-se agora",
"encerrar interação agora",
"concluir diálogo agora",
"encerrar chat imediatamente",
"terminar sessão agora",
"finalizar conversa agora",
"encerrar interação imediatamente",
"concluir atendimento agora",
"terminar ação agora",
"fechar chat agora",
"despedir-se agora",
"cancelar pedido agora",
"encerrar conexão agora",
"parar imediatamente",
"parar interação agora",
"sair de vez agora",
"cancelar operação agora",
"encerrar discussão agora",
"encerrar interação agora",
"finalizar interação agora",
"desligar agora",
"encerrar chat agora",
"terminar chat agora",
"encerrar chamada agora",
"finalizar atendimento agora",
"terminar conversação agora",
"fechar atendimento agora",
"encerrar atendimento agora",
"desconectar-se agora",
"encerrar interação agora",
"concluir diálogo agora",
"encerrar chat imediatamente",
"terminar sessão agora",
"finalizar conversa agora",
"encerrar interação imediatamente",
"concluir atendimento agora",
"terminar ação agora",
"fechar chat agora",
"despedir-se agora",
"cancelar pedido agora",
"encerrar conexão agora",
"parar imediatamente",
"parar interação agora",
"sair de vez agora",
"cancelar operação agora",
"encerrar discussão agora",
"encerrar interação agora",
"finalizar interação agora",
"desligar agora",
"encerrar chat agora",
"terminar chat agora",
"encerrar chamada agora",
"finalizar atendimento agora",
"terminar conversação agora",
"fechar atendimento agora",
"encerrar atendimento agora",
"desconectar-se agora",
"encerrar interação agora",
"concluir diálogo agora",
"encerrar chat imediatamente",
"terminar sessão agora",
"finalizar conversa agora",
"encerrar interação imediatamente",
"concluir atendimento agora",
"terminar ação agora",
"fechar chat agora",
"despedir-se agora",
"cancelar pedido agora",
"encerrar conexão agora",
"parar imediatamente",
"parar interação agora",
"sair de vez agora",
"cancelar operação agora",
"encerrar discussão agora",
"encerrar interação agora",
"finalizar interação agora",
"desligar agora",
"encerrar chat agora",
"terminar chat agora",
"encerrar chamada agora",
"finalizar atendimento agora",
"terminar conversação agora",
"fechar atendimento agora",
"encerrar atendimento agora",
"desconectar-se agora",
"encerrar interação agora",
"concluir diálogo agora",
"encerrar chat imediatamente",
"terminar sessão agora",
"finalizar conversa agora",
"encerrar interação imediatamente",
"concluir atendimento agora",
"terminar ação agora",
"fechar chat agora",
"despedir-se agora",
"cancelar pedido agora",
"encerrar conexão agora",
"parar imediatamente",
"parar interação agora",
"sair de vez agora",
"cancelar operação agora",
"encerrar discussão agora",
"encerrar interação agora",
"finalizar interação agora",
"desligar agora",
"encerrar chat agora",
"terminar chat agora",
"encerrar chamada agora",
"finalizar atendimento agora",
"terminar conversação agora",
"fechar atendimento agora",
"encerrar atendimento agora",
"desconectar-se agora",
"encerrar interação agora",
"concluir diálogo agora",
"encerrar chat imediatamente",
"terminar sessão agora",
"finalizar conversa agora",
"encerrar interação imediatamente",
"concluir atendimento agora",
"terminar ação agora",
"fechar chat agora",
"despedir-se agora",
"cancelar pedido agora",
"encerrar conexão agora",
"parar imediatamente",
"parar interação agora",
"sair de vez agora",
"cancelar operação agora",
"encerrar discussão agora",
"encerrar interação agora",
"finalizar interação agora",
"desligar agora",
"encerrar chat agora",
"terminar chat agora",
"encerrar chamada agora",
"finalizar atendimento agora",
"terminar conversação agora",
"fechar atendimento agora",
"encerrar atendimento agora",
"desconectar-se agora",
"encerrar interação agora",
"concluir diálogo agora",
"encerrar chat imediatamente",
"terminar sessão agora",
"finalizar conversa agora",
"encerrar interação imediatamente",
"concluir atendimento agora",
"terminar ação agora",
"fechar chat agora",
"despedir-se agora",
"cancelar pedido agora",
"encerrar conexão agora",
"parar imediatamente",
"parar interação agora",
"sair de vez agora",
"cancelar operação agora",
"encerrar discussão agora",
"encerrar interação agora",
"finalizar interação agora",
"desligar agora",
"encerrar chat agora",
"terminar chat agora",
"encerrar chamada agora",
"finalizar atendimento agora",
"terminar conversação agora",
"fechar atendimento agora",
"encerrar atendimento agora",
"desconectar-se agora",
"encerrar interação agora",
"concluir diálogo agora",
"encerrar chat imediatamente",
"terminar sessão agora",
"finalizar conversa agora",
"encerrar interação imediatamente",
"concluir atendimento agora",
"terminar ação agora",
"fechar chat agora",
"despedir-se agora",
"cancelar pedido agora",
"encerrar conexão agora",
"parar imediatamente",
"parar interação agora",
"sair de vez agora",
"cancelar operação agora",
"encerrar discussão agora",
"encerrar interação agora",
"finalizar interação agora",
"desligar agora",
"encerrar chat agora",
"terminar chat agora",
"encerrar chamada agora",
"finalizar atendimento agora",
"terminar conversação agora",
"fechar atendimento agora",
"encerrar atendimento agora",
"desconectar-se agora",
"encerrar interação agora",
"concluir diálogo agora",
"encerrar chat imediatamente",
"terminar sessão agora",
"finalizar conversa agora",
"encerrar interação imediatamente",
"concluir atendimento agora",
"terminar ação agora",
"fechar chat agora",
"despedir-se agora",
"cancelar pedido agora",
"encerrar conexão agora",
"parar imediatamente",
"parar interação agora",
"sair de vez agora",
"cancelar operação agora",
"encerrar discussão agora",
"encerrar interação agora",
"finalizar interação agora",
"desligar agora",
"encerrar chat agora",
"terminar chat agora",
"encerrar chamada agora",
"finalizar atendimento agora",
"terminar conversação agora",
"fechar atendimento agora",
"encerrar atendimento agora",
"desconectar-se agora",
"encerrar interação agora",
"concluir diálogo agora",
"encerrar chat imediatamente",
"terminar sessão agora",
"finalizar conversa agora",
"encerrar interação imediatamente",
"concluir atendimento agora",
"terminar ação agora",
"fechar chat agora",
"despedir-se agora",
"cancelar pedido agora",
"encerrar conexão agora",
"parar imediatamente",
"parar interação agora",
"sair de vez agora",
"cancelar operação agora",
"encerrar discussão agora",
"encerrar interação agora",
"finalizar interação agora",
"desligar agora",
"encerrar chat agora",
"terminar chat agora",
"encerrar chamada agora",
"finalizar atendimento agora",
"terminar conversação agora",
"fechar atendimento agora",
"encerrar atendimento agora",
"desconectar-se agora",
"encerrar interação agora",
"concluir diálogo agora",
"encerrar chat imediatamente",
"terminar sessão agora",
"finalizar conversa agora",
"encerrar interação imediatamente",
"concluir atendimento agora",
"terminar ação agora",
"fechar chat agora",
"despedir-se agora",
"cancelar pedido agora",
"encerrar conexão agora",
"parar imediatamente",
"parar interação agora",
"sair de vez agora",
"cancelar operação agora",
"encerrar discussão agora",
"encerrar interação agora",
"finalizar interação agora",
"desligar agora",
"encerrar chat agora",
"terminar chat agora",
"encerrar chamada agora",
"finalizar atendimento agora",
"terminar conversação agora",
"fechar atendimento agora",
"encerrar atendimento agora",
"desconectar-se agora",
"encerrar interação agora",
"concluir diálogo agora",
"encerrar chat imediatamente",
"terminar sessão agora",
"finalizar conversa agora",
"encerrar interação imediatamente",
"concluir atendimento agora",
"terminar ação agora",
"fechar chat agora",
"despedir-se agora",
"cancelar pedido agora",
"encerrar conexão agora",
"parar imediatamente",
"parar interação agora",
"sair de vez agora",
"cancelar operação agora",
"encerrar discussão agora",
"encerrar interação agora",
"finalizar interação agora",
"desligar agora",
"encerrar chat agora",
"terminar chat agora",
"encerrar chamada agora",
"finalizar atendimento agora",
"terminar conversação agora",
"fechar atendimento agora",
"encerrar atendimento agora",
"desconectar-se agora",
"encerrar interação agora",
"concluir diálogo agora",
"encerrar chat imediatamente",
"terminar sessão agora"
];
const perguntarNomeBot = [
  // Perguntas diretas
  "qual seu nome?",
  "Qual seu nome",
  "Com que eu falo?",
  "como voce se chama?",
  "como voce se chama",
  "quem é você",
  "quem é voce?",
  "seu nome?",
  "seu nome",
  "quem é o bot",
  "qual o nome do bot",
  "como chama o bot",
  "quem fala",
  "quem está falando",
  "quem ta falando",
  "quem tá falando",
  "bar do link",
  "esse é o bar do link?",
  "voce é o bar do link?",
  "voce é o bot do bar do link?",
  "é o bar do link",
  "o bot do bar do link",
  "quem é o bar do link",
  "como chama o bar",
  "qual o nome do bar",
  "esse bar tem nome",
  "bot bar do link é você?",
  "bot bar do link"
];

const pedirCardapio = [
  "quero ver o cardapio",
  "cardapio",
  "o que tem de bom?",
  "o que tem de bom",
  "qual o cardápio?",
  "o que tem no cardápio?",
  "me mostre o cardápio",
  "quais opções de comida você tem?",
  "o que você serve?",
  "quais pratos você oferece?",
  "tem cardápio?",
  "quero ver o cardápio",
  "me envie o cardápio",
  "quais são os pratos disponíveis?",
  "o que posso pedir?",
  "quais são as opções?",
  "quais são os itens do cardápio?",
  "quais são os pratos do cardápio?",
  "quais são as bebidas disponíveis?",
  "quais são os lanches disponíveis?",
  "quais são os acompanhamentos?",
  "quais são as sobremesas?",
  "quais são as opções de bebidas?",
  "quais são as opções de lanches?",
  "quais são as opções de acompanhamentos?",
  "quais são as opções de sobremesas?",
  "quais são as opções de bebidas alcoólicas?",
  "quais são as opções de bebidas não alcoólicas?",
  "quais são as opções de lanches rápidos?",
  "quais são as opções de pratos principais?",
  "quais são as opções de petiscos?",
  "quais são as opções de pratos vegetarianos?",
  "quais são as opções de pratos veganos?",
  "quais são as opções sem glúten?",
  "quais são as opções sem lactose?",
];


// Exporte as listas para uso em outros arquivos usando CommonJS
module.exports = {
  pedirCardapio,
  removerPedido,
  pedidos,
  verPedido,
  greetings,
  confirmarPedido,
  encerrar,
  perguntarNomeBot,
};
